(function(){function q(a){var b=document.createElement("div"),c=[];fish.all(b).html(a);for(a=0;a<b.childNodes.length;a++)b.childNodes[a].nodeType===1&&c.push(b.childNodes[a]);return fish.all(c)}function r(a){a=a||{};var b=function(){};b={css:"",width:0,height:0,open:false,startTime:fish.parseTime(new Date),endTime:"2099-01-01",inputElem:fish.dom(this),formatInputElemAtStart:false,showPast:false,showDay:false,now:fish.parseTime(new Date),focus:fish.parseTime(new Date),eachHeight:28,eachWidth:28,monthNum:2,
ajaxUrl:"",bodyTemp:'<iframe class="if" src="http://img1.40017.cn/cn/new_ui/public/images/png_cover.png"></iframe><div class="date"><div class="top clearfix"></div><div class="calCanvas"></div></div>',titleTemp:'<div class="floatL monthTitle"><h4 class="lastText  mCalTitleFir" ><span class="date_title">...</span></h4></div>',prevBtnTemp:'<span class="lastMonthBg date_lastSpan"><span class="lastMonth"></span></span>',nextBtnTemp:'<span class="nextMonthBg date_nextSpan"><span class="nextMonth"></span></span>',
cache:{},fn:b,ajaxFn:b,monthChangeStyle:"",_monthTimes:1,mouseover:b,mouseout:b,beforeOpen:b,afterClose:b,beforePrevFn:b,afterPrevFn:b,beforeNextFn:b,afterNextFn:b,processDataFn:b,dateTempleteFn:b};var c=fish.lang.proto(mCalFn);fish.lang.extend(b,a);fish.lang.extend(c,b);return c.init()}function m(a){a=fish.parseDate(a,{months:1});a.setDate(0);return a.getDate()}function o(a){a=fish.parseDate(a);a.setDate(1);return p.charAt(a.getDay())}function u(a,b,c){var d=fish.parseDate(a),e=fish.parseDate(a);
b=fish.parseDate(b);c=fish.parseDate(c);d.setDate(1);e.setDate(m(a));a=d.getTime();e=e.getTime();b=b.getTime();c=c.getTime();b=[a,e,b,c].sort(function(g,f){return g-f});return b[1]===c||b[1]===e?{start:0,end:0}:{start:(new Date(b[1])).getDate(),end:(new Date(b[2])).getDate()}}function v(a){a=a||{};var b=function(){};b={width:0,cal:"",now:"",today:"",tomorrow:"",month:fish.parseTime(new Date),eachHeight:28,eachWidth:28,__elem:null,dataUrl:"",fn:b,ajaxFn:b,showPast:false,mouseover:b,mouseout:b,calTemp:function(){var d=
[],e;d.push('<div class="contentTime clearfix"><table cellspacing="0" cellpadding="0" border="0" ><tbody><tr>');p.split("").forEach(function(h){d.push("<th>"+h+"</th>")});d.push("</tr>");for(var g=0;g<6;g++){d.push('<tr calweek="'+(g+1)+'">');for(var f=0;f<7;f++){e=p.charAt(f);d.push('<td><div calday="'+e+'" class="itemWrap '+(e==="\u516d"?"sat":e==="\u65e5"?"sun":"")+'"><span class="dateWrap">&nbsp;</span><div class="userWrap"></div></div></td>')}d.push("</tr>")}d.push('</tbody></table><i class="monthBg"></i></div>');
return d.join("")}(),reloadData:false,startDate:1,endDate:31,firstDay:"",processDataFn:b,dateTempleteFn:b,startTime:"1970-01-01",endTime:"2099-01-01"};var c=fish.lang.proto(mMonthFn);fish.lang.extend(b,a);fish.lang.extend(c,b);c.init();return c}function w(a){a=parseInt(a);if(a<10)a="0"+a;return a+""}var x={"2013-01-01":{name:"\u5143\u65e6"},"2013-02-09":{name:"\u9664\u5915"},"2013-02-10":{name:"\u6625\u8282"},"2013-02-24":{name:"\u5143\u5bb5"},"2013-04-04":{name:"\u6e05\u660e"},"2013-05-01":{name:"5.1"},
"2013-06-01":{name:"6.1"},"2013-06-12":{name:"\u7aef\u5348"},"2013-08-13":{name:"\u4e03\u5915"},"2013-09-19":{name:"\u4e2d\u79cb"},"2013-10-01":{name:"\u56fd\u5e86"},"2013-12-25":{name:"\u5723\u8bde"},"2014-01-01":{name:"\u5143\u65e6"},"2012-04-04":{name:"\u6e05\u660e"},"2012-05-01":{name:"5.1"},"2012-06-01":{name:"6.1"},"2012-06-23":{name:"\u7aef\u5348"},"2012-08-23":{name:"\u4e03\u5915"},"2012-09-30":{name:"\u4e2d\u79cb"},"2012-10-01":{name:"\u56fd\u5e86"},"2012-12-25":{name:"\u5723\u8bde"}},n=
{},p="\u65e5\u4e00\u4e8c\u4e09\u56db\u4e94\u516d",y=0;mCalFn={init:function(){var a=this;if(this.inputElem&&(this.id=fish.all(this.inputElem).attr("data-mcalid"))&&n[this.id]){n[this.id].set();return n[this.id]}else{var b=fish.browser();b=b.name==="ms"&&b.version<9?"static":"scroll";this.monthChangeStyle=this.monthChangeStyle?this.monthChangeStyle:b;this._monthTimes=this.monthChangeStyle==="static"?1:3;this.id=++y;this.__inputElem=fish.all(this.inputElem);this.__inputElem.attr("data-mcalid",this.id);
this.__calElem=q("<div id='mCalendar"+this.id+"' class='mCalendar' style='position:absolute;display:block;top:0px;left:-1000px'></div>");fish.one("body").html("top",this.__calElem);this.__calElem.html("top",this.bodyTemp);this.__topElem=fish.all(".top",this.__calElem);this.__topElem.html("top",this.prevBtnTemp);this.__topElem.html("top",this.nextBtnTemp);this.__canvasElem=fish.one(".calCanvas",this.__calElem);this.month=[];this.__monthHolderElem=fish.one(".date",this.__calElem);for(var c=0;c<this.monthNum;c++)this.__topElem.html("top",
this.titleTemp);this.__monthTitleElem=fish.all(".monthTitle",this.__topElem);this._setNowAndFoucs();var d,e;b=this.monthNum*(this.monthChangeStyle==="static"?1:3);var g=this.monthChangeStyle==="static"?0:this.monthNum;for(c=0;c<b;c++)(function(f){a.month[c]=new v({width:d?d:0,height:e?e:0,cal:a,now:a.now,today:fish.parseTime(),month:fish.parseTime(a.focus,{months:c-g}),eachHeight:a.eachHeight,eachWidth:a.eachWidth,startTime:a.startTime,endTime:a.endTime,processDataFn:a.processDataFn,dateTempleteFn:a.dateTempleteFn,
showPast:a.showPast,dataUrl:a.ajaxUrl,fn:function(h){a._setFn(h,f)},mouseover:a.mouseover,mouseout:a.mouseout});a.month[c].insertTo(a.__canvasElem);d=a.month[c].width;e=a.month[c].height})(c);this.monthGroup={a:[],b:[],c:[],prev:"a",focus:"b",next:"c"};if(this.monthChangeStyle==="static")for(c=0;c<this.month.length;c++)this.monthGroup.b.push(this.month[c]);else if(this.monthChangeStyle==="scroll")for(c=0;c<this.month.length;c++)if(c<this.monthNum)this.monthGroup.a.push(this.month[c]);else c<this.monthNum*
2?this.monthGroup.b.push(this.month[c]):this.monthGroup.c.push(this.month[c]);this.set({},true);this.__monthTitleElem.css("width:"+this.month[0].width+"px");this.__prevBtn=fish.one(".lastMonthBg",this.__calElem).on("click",function(){this.beforePrevFn&&this.beforePrevFn.call(a);a.goPrev()});this.__nextBtn=fish.one(".nextMonthBg",this.__calElem).on("click",function(){this.beforeNextFn&&this.beforeNextFn.call(a);a.goNext()});fish.all(this.elem).on("click",function(){a.show()});this.__inputElem.on("focus",
function(){a.show()});this.__inputElem.on("mousedown",function(){a._calElemTouch=true});this.__inputElem.on("mouseup",function(){a._calElemTouch=false});this.__inputElem.on("blur",function(){setTimeout(function(){if(!a._calElemTouch){a.hide();this._calElemTouch=false}},0)});b=fish.all([fish.dom(this.__calElem),fish.dom(this.__inputElem)]);if(this.elem){b[b.length]=fish.dom(this.elem);b.length++}switch(this.showType){case "pop":break;case "static":break;default:this.__calElem.effect({type:"click",
elem:b,interShow:false,interFn:function(){fish.dom(a.__inputElem).blur()}})}this.__calElem.on("mousedown",function(){a._calElemTouch=true});this.__calElem.on("mouseup",function(){a._calElemTouch=false});a.setWH();a.open?a.show(false,true):a.hide();return n[this.id]=this}},setWH:function(){var a=this.month[0].width*this.monthNum;this.__canvasElem.css("width:"+a+"px;height:"+this.month[0].height+"px");this.show(true);this.height=this.__topElem.height()+this.__canvasElem.height();this.__monthHolderElem.css("width:"+
a+"px;height:"+this.height+"px");this.width=a+4;this.height+=4;fish.one("iframe",this.__calElem).css("width:"+this.width+"px;height:"+this.height+"px");this.__calElem.css("width:"+this.width+"px;height:"+this.height+"px");this.hide()},_setNowAndFoucs:function(){var a;this.now=fish.parseTime(fish.one(this.inputElem).val());this.formatInputElemAtStart&&fish.one(this.inputElem).val(this.now);a=fish.parseDate(this.now);a.setDate(1);this.focus=fish.parseTime(a)},set:function(a,b){var c=this.monthChangeStyle===
"static"?0:this.monthNum;a=a||{};var d=this;fish.lang.extend(this,a);this._setNowAndFoucs();this.setMonthTitle();if(!b)for(var e=0;e<this.month.length;e++)(function(g){d.month[e].setDate({now:d.now,today:fish.parseTime(),month:fish.parseTime(d.focus,{months:e-c}),startTime:d.startTime,endTime:d.endTime,showPast:d.showPast,processDataFn:d.processDataFn,dateTempleteFn:d.dateTempleteFn,dataUrl:d.ajaxUrl,fn:function(f){d._setFn(f,g)},mouseover:d.mouseover,mouseout:d.mouseout})})(e);if(this.monthChangeStyle===
"static")this._setStatic();else this.monthChangeStyle==="scroll"&&this._setScroll();this.monthGroup[this.monthGroup.focus].forEach(function(g){g.setUserDate()})},_setFn:function(a,b){var c=this,d;this.month.forEach(function(e){e.setNow(a)});d=this.month[b].getItemElem(fish.parseDate(a).getDate());this.setValue(a);setTimeout(function(){c.hide()},0);this.fn&&this.fn.call(this,a,d)},setValue:function(a){this.now=fish.parseTime(a);this.__inputElem.val(this.now)},setMonth:function(a,b){this.monthGroup[this.monthGroup[a]].forEach(function(c,
d){c.setDate({month:fish.parseTime(b,{months:d})})})},setMonthUserDate:function(a){this.monthGroup[this.monthGroup[a]].forEach(function(b){b.setUserDate()})},show:function(a,b){var c,d=this;if(a)this.__calElem.css("position:absolute;display:block;top:0px;left:-1000px");else{var e=fish.one(this.inputElem).offset(),g=fish.one(this.inputElem).height(),f=fish.one(window).width(),h=this.width,j;switch(d.showType){case "pop":fish.all(d.__calElem).css("position:static");fish.require("mPop",function(){if(fish.all(d.__calElem).getCss("display")!==
"block"){fish.all(d.__calElem).css("display:block;");fish.mPop({content:d.__calElem,afterClose:function(){fish.all(d.__calElem).css("display:none;")}})}});break;case "static":fish.all(d.__calElem).css("position:relative;display:block;left:0;");fish.one(d.inputElem).css("display:block").html("top",d.__calElem);break;default:j=f-e.left>=h+20?e.left:e.left-20-(h-(f-e.left));c=e.top+g}b||this.set();setTimeout(function(){d.__calElem.css("display:block;top:"+c+"px;left:"+j+"px")},0)}},hide:function(){switch(this.showType){case "pop":fish.require("mPop",
function(){fish.mPop.close()});break;case "static":break;default:this.__calElem.css("display:none")}},goPrev:function(){this.focus=fish.parseTime(this.focus,{months:-this.monthNum});if(this.monthChangeStyle==="static"){this.setMonth("focus",this.focus);this.setMonthUserDate("focus",this.focus)}else if(this.monthChangeStyle==="scroll"){var a=fish.parseTime(this.focus,{months:-this.monthNum});this._scrollPrev();this.setMonth("prev",a);this.setMonthUserDate("focus",a)}this.setMonthTitle();this.afterPrevFn&&
this.afterPrevFn.call(this)},goNext:function(){this.focus=fish.parseTime(this.focus,{months:this.monthNum});if(this.monthChangeStyle==="static"){this.setMonth("focus",this.focus);this.setMonthUserDate("focus",this.focus)}else if(this.monthChangeStyle==="scroll"){var a=fish.parseTime(this.focus,{months:this.monthNum});this._scrollNext();this.setMonth("next",a);this.setMonthUserDate("focus",a)}this.setMonthTitle();this.afterNextFn&&this.afterNextFn.call(this)},_monthStyle:function(){var a=fish.browser();
return a.name==="ms"&&a.version<9?function(b){return"left:"+b+"px"}:function(b){return"-webkit-transform:translateX("+b+"px);-ms-transform:translateX("+b+"px);-moz-transform:translateX("+b+"px);-o-transform:translateX("+b+"px);"}}(),_scrollTo:function(a,b){var c=0,d=0,e=this,g=this.monthGroup[a];switch(b){case "prev":c=-this.monthNum;a==="next"?d=0:d=1;break;case "next":c=this.monthNum;a==="prev"?d=0:d=1;break;case "focus":d=2}this.monthGroup[g].forEach(function(f,h){f.css(e._monthStyle((h+c)*f.width));
f.z(d)})},_setScroll:function(){this.monthGroup.prev="a";this.monthGroup.focus="b";this.monthGroup.next="c";this._scrollTo("focus","focus");this._scrollTo("next","next");this._scrollTo("prev","prev")},_scrollPrev:function(){var a=this.monthGroup.focus,b=this.monthGroup.prev,c=this.monthGroup.next;this._scrollTo("focus","next");this._scrollTo("next","prev");this._scrollTo("prev","focus");this.monthGroup.focus=b;this.monthGroup.prev=c;this.monthGroup.next=a},_scrollNext:function(){var a=this.monthGroup.focus,
b=this.monthGroup.prev,c=this.monthGroup.next;this._scrollTo("focus","prev");this._scrollTo("next","focus");this._scrollTo("prev","next");this.monthGroup.focus=c;this.monthGroup.prev=a;this.monthGroup.next=b},_setStatic:function(){var a=this;this.monthGroup.focus=this.monthGroup.prev=this.monthGroup.next="b";this.monthGroup.b.forEach(function(b,c){b.css(a._monthStyle(c*b.width))})},setMonthTitle:function(){var a=this;this.__monthTitleElem.each(function(b,c){var d=fish.parseDate(a.focus,{months:c});
fish.one(".date_title",b).html(d.getFullYear()+"\u5e74"+(d.getMonth()+1)+"\u6708")})},setAjaxUrl:function(a){this.ajaxUrl=a}};mMonthFn={init:function(){var a=this;if(!this.__elem){this.__elem=q(this.calTemp);this.__itemElems=fish.all(".itemWrap",this.__elem);this.__dateElems=fish.all(".dateWrap",this.__elem);this.__userElems=fish.all(".userWrap",this.__elem);this.__itemElems.css("width:"+this.eachWidth+"px;height:"+this.eachHeight+"px");this.__bgElem=fish.all(".monthBg",this.__elem);this.firstDay=
o(this.month);this.setDate();this.__itemElems.on("click",function(){var b=fish.one(this).attr("day"),c=fish.parseDate(a.month);c.setDate(parseInt(b,10));if(fish.one(this).hasClass("spanEnable")&&b){b=fish.parseTime(c);a.fn&&a.fn.call(a,b)}}).hover(function(){var b=fish.one(this);if(b.hasClass("spanEnable")){var c=b.attr("day"),d=fish.parseDate(a.month);d.setDate(parseInt(c,10));d=fish.parseTime(d);b.addClass("spanHover");a.mouseover&&a.mouseover.call(a,d,this,a.formatData?a.formatData[parseInt(c,
10)-1]:undefined)}},function(){var b=fish.one(this);if(b.hasClass("spanEnable")){var c=b.attr("day"),d=fish.parseDate(a.month);d.setDate(parseInt(c,10));c=fish.parseTime(d);a.mouseout&&a.mouseout.call(a,c)}b.removeClass("spanHover")})}},appendTo:function(a){fish.one(a).html("bottom",this.__elem);if(!this.width&&!this.height){this.width=this.__elem.width();this.height=this.__elem.height()}this.__bgElem.css("width:"+this.width+"px;height:"+this.height+"px")},insertTo:function(a){fish.one(a).html("top",
this.__elem);if(!this.width&&!this.height){this.width=this.__elem.width();this.height=this.__elem.height()}this.__bgElem.css("width:"+this.width+"px;height:"+this.height+"px;line-height:"+this.height+"px")},css:function(a){this.__elem.css(a)},z:function(a){this.__elem.css("z-index:"+a)},_setValidDate:function(){var a=u(this.month,this.startTime,this.endTime);this.startDate=a.start;this.endDate=a.end},setDate:function(a){a=a||{};var b=this;fish.lang.extend(this,a);var c=fish.parseDate(this.month);
c.setDate(1);this.month=fish.parseTime(c);this.monthIndex=fish.parseDate(this.month).getMonth()+1;this.tomorrow=fish.parseTime(this.today,{days:1});this._setValidDate();var d=o(this.month),e=0,g="",f=false,h=false,j,i,k,l=m(this.month);this.__itemElems.each(function(z,s){i=fish.one(b.__itemElems[s]);k=fish.one(b.__dateElems[s]);i.removeClass("spanNow spanDate spanEnable spanHover spanSpec");if((f||fish.one(z).attr("calday")===d)&&!h){f=true;e++;c.setDate(e);g=fish.parseTime(c);j=x[fish.parseTime(g)];
if(g===b.today){i.addClass("spanSpec");j={name:"\u4eca\u5929"}}else if(g===b.tomorrow){i.addClass("spanSpec");j={name:"\u660e\u5929"}}else g===b.now&&i.addClass("spanNow");i.attr("day",e);j?k.html(j.name):k.html(e);i.addClass("spanDate");if(b.startDate<=e&&e<=b.endDate||b.showPast){i.addClass("spanEnable");j&&i.addClass("spanSpec")}if(l===e)h=true}else{k.html("");i.attr("day","")}});this.setNow(this.now);this.__bgElem.html(this.monthIndex)},setNow:function(a){var b=fish.parseDate(a),c=fish.parseDate(this.month);
this.clearNow();b.getFullYear()===c.getFullYear()&&b.getMonth()===c.getMonth()&&this.__itemElems.each(function(d){d=fish.one(d);if(d.attr("day")==b.getDate()){d.addClass("spanNow");this.now=fish.parseTime(a);return false}})},getItemElem:function(a){if(a==undefined)throw"param missing!check getItemElem";else if(isNaN(a))throw"param:day should be numberType!check getItemElem";var b;this.__itemElems.each(function(){var c=this.getAttribute("day");if(a==c){b=this;return false}});return b},clearNow:function(){this.__itemElems.removeClass("spanNow");
this.now=""},setUserDate:function(){if(this.dataUrl&&this.processDataFn&&this.dateTempleteFn){var a=this,b,c,d=this.dataUrl,e=fish.parseDate(this.month);d=d.replace("{month}",w(e.getMonth()+1));d=d.replace("{year}",e.getFullYear());this.__bgElem.addClass("loadingbg");b=fish.parseDate(a.month);c=m(b);if(this.reloadData||!this.cal.cache[this.month]){if(this.ajaxObj)try{this.ajaxObj.abort();this.ajaxObj=null}catch(g){}this.ajaxObj=fish.ajax({url:d,type:"json",fn:function(f){if(f){a.cal.cache[a.month]=
f;a.ajaxFn&&a.ajaxFn(f);a.formatData=a.processDataFn(f,c,b.getFullYear(),b.getMonth()+1);a._setUserDate();a.__bgElem.removeClass("loadingbg")}}})}else{a.formatData=a.processDataFn(this.cal.cache[this.month],c,b.getFullYear(),b.getMonth()+1);a._setUserDate();this.__bgElem.removeClass("loadingbg")}}},_setUserDate:function(){var a=false,b=false,c=this,d,e=0,g=o(this.month),f=fish.parseDate(this.month),h=f.getFullYear(),j=f.getMonth()+1,i=m(this.month);this.__userElems.each(function(k,l){if((a||fish.one(k).getParent(".itemWrap").attr("calday")===
g)&&!b){a=true;d=c.dateTempleteFn(h,j,e,c.formatData[e]);fish.one(c.__userElems[l]).html(d?d:"");e++;d===false&&fish.one(c.__itemElems[l]).removeClass("spanEnable");if(i===e)b=true}else fish.one(c.__userElems[l]).html("")})}};var t=true;fish.extend({mCal:function(){var a=this,b=arguments;if(t){setTimeout(function(){r.apply(a,b)},1E3);t=false}else r.apply(a,b)},preventInput:function(a){fish.all(a?a:this).each(function(b){if(!b.getAttribute("_preventInput_")){b.style.imeMode="disabled";b.onkeydown=
function(c){fish.preventDefault(c)};b.oncontextmenu=function(){return false};b.onselectstart=function(){return false};b.setAttribute("_preventInput_","true")}})},recoverInput:function(a){fish.all(a?a:this).each(function(b){if(b.getAttribute("_preventInput_")){b.style.imeMode="";b.onkeydown=b.oncontextmenu=b.onselectstart=null;b.setAttribute("_preventInput_","")}})}})})();
