(function(){function w(a,c,d){z.hasCallOnce=false;return z(a,c,d)}function z(a,c,d){var b=/\s(\d+):?(\d+)?:?(\d+)?/,f;if(typeof a==="object"){b=a.getFullYear();var g=a.getMonth()+1,i=a.getDate(),h=a.getHours(),j=a.getMinutes(),k=a.getSeconds()}else{a=a?a:"";f=b.exec(a);k=a.split("-");b=parseInt(k[0],10);g=parseInt(k[1],10);i=parseInt(k[2],10);k=j=h=0;if(f){if(f[1])h=parseInt(f[1],10);if(f[2])j=parseInt(f[2],10);if(f[3])k=parseInt(f[3],10)}}var r=new Date;f={years:0,months:0,days:0,hours:0,minutes:0,
seconds:0,timeMode:null};if(b&&g&&i){fish.lang.extend(f,c);b+=f.years;g+=f.months;i+=f.days;h+=f.hours;j+=f.minutes;k+=f.seconds;k=new Date(b,g-1,i,h,j,k);b=k.getFullYear();g=k.getMonth()+1;i=k.getDate();h=k.getHours();j=k.getMinutes();k=k.getSeconds();g=g<10?"0"+g:g;i=i<10?"0"+i:i;h=h<10?"0"+h:h;j=j<10?"0"+j:j;k=k<10?"0"+k:k;f=f.timeMode?f.timeMode.replace("YYYY",b).replace("MM",g).replace("DD",i).replace("hh",h).replace("mm",j).replace("ss",k):[b,g,i].join("-");return f=d?{y:b,m:g,d:i,h:h,mi:j,
s:k}:f}else if(!arguments.callee.hasCallOnce){arguments.callee.hasCallOnce=true;return arguments.callee([r.getFullYear(),r.getMonth()+1,r.getDate()].join("-"),c,d)}}function A(a){fish.all(a?a:this).each(function(c){if(!c.getAttribute("_preventInput_")){c.style.imeMode="disabled";c.onkeydown=function(d){fish.preventDefault(d)};c.oncontextmenu=function(){return false};c.onselectstart=function(){return false};c.setAttribute("_preventInput_","true")}})}function B(a,c){var d=fish.dom(a.inputElem);if(d){A(d);
if(x)a.calElem=x;else{var b=document.createElement("div");b.id="mCalendar";b.onselectstart=function(){return false};document.body.insertBefore(b,document.body.firstChild);var f=document.createElement("iframe");f.className="if";f.src="http://img1.40017.cn/cn/new_ui/public/images/png_cover.png";b.appendChild(f);f=document.createElement("div");f.className="date";b.appendChild(f);var g=document.createElement("div");f.appendChild(g);g.className="top";var i=fish.browser("webkit")?"webkit_nextMonth":"nextMonth";
g.innerHTML="<span class='lastMonthBg' id='date_lastSpan'><span class='lastMonth' ></span></span><h4 class='lastText' id='tbl_lastMonth_input'>xxxx\u5e74xx\u6708</h4><span class='nextMonthBg' id='date_nextSpan'><span class='"+i+"' ></span></span><h4 class='nextText' id='tbl_nextMonth_input'>xxxx\u5e74xx\u6708</h4>";g=document.createElement("div");g.className="contentTime1 contentTime clearfix";g.innerHTML="<table cellspacing='0' cellpadding='0' id='tbl_lastMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg' >1</i>";
f.appendChild(g);g=document.createElement("div");g.className="contentTime2 contentTime clearfix";g.innerHTML="<table cellspacing='0' cellpadding='0' id='tbl_nextMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg'>12</i>";f.appendChild(g);a.calElem=x=b;b.className="mCalendar";fish.all(a.calElem).css("display:none;")}fish.dom("#date_lastSpan").onclick=function(){var j=a.inputElem._mCalDate_;
j._addNum-=4;s("#tbl_lastMonth",j);s("#tbl_nextMonth",j)};fish.dom("#date_nextSpan").onclick=function(){var j=a.inputElem._mCalDate_;s("#tbl_lastMonth",j);s("#tbl_nextMonth",j)};if(!a.inputElem.bindCal){var h;if(a.elem){h=fish.all(a.elem);h[h.length]=a.inputElem;h.length++}b=h?h:a.inputElem;fish.one(a.calElem).effect({elem:b,type:"click",interShow:false,interFn:function(){var j=a.inputElem._mCalDate_;j.time="";B(j,true)}});a.inputElem.bindCal=true}a.calElem.className="mCalendar"+(a.css?" "+a.css:
"");a._lastTime=a.time=d.value=w(a.time?a.time:d.value);b=parseInt(a.time.split("-")[1],10);a._addNum=b&&!(b%2)?-1:0;C=a.inputElem._mCalDate_=a;if(c){s("#tbl_lastMonth",a);s("#tbl_nextMonth",a);b=fish.one(d).offset();d=fish.one(d).height();h=fish.one(window).width();h=h-b.left>=470?b.left:b.left-20-(450-(h-b.left));fish.all(a.calElem).css("top:"+(b.top+d)+"px; left:"+h+"px;");fish.all(a.calElem).css("display:block;")}else a._addNum+=2}}function s(a,c){var d=fish.dom(a),b=fish.dom(a+"_input"),f=d.parentNode.getElementsByTagName("i"),
g=d.getAttribute("inited")=="true",i=w(c.time.split("-")[0]+"-"+c.time.split("-")[1]+"-01",{months:c._addNum}).split("-");if(f.length>0)f[0].innerHTML=parseInt(i[1],10);b.innerHTML=i[0]+"\u5e74"+i[1]+"\u6708";b=i[0]+"-"+i[1]+"-1";c._addNum++;b=new Date(Date.parse(b.replace(/-/g,"/")));f=b.getDay();b.setMonth(b.getMonth()+1);b.setDate(0);var h,j=b.getDate(0);if(f!=7)j+=f;var k,r;if(g){k=fish.all("tr",d);tds=fish.all("td",d);r=fish.all("span",d)}for(var p=1;p<=42;p++){var o=p-f;if(p%7==1)h=g?k[parseInt(p%
7,10)]:d.insertRow(d.rows.length);var l,e;if(g){l=tds[p-1];e=r[p-1]}else{l=h.insertCell(p%7-1);l.innerHTML="  ";e=document.createElement("span");l.appendChild(e)}if(f!=7&&p<=f||p>j){l.className="td02";e.innerHTML=" ";e.className="spanOut";e.onmouseover=e.onmouseout=e.onclick=null}else{l.className="td01";l=G(b.getFullYear(),b.getMonth()+1,o);if(l==-1){e.innerHTML=o;e.className="spanOut";e.setAttribute("s","false");e.setAttribute("d",o)}else{e.innerHTML="";e.className=l.className;e.setAttribute("s",
"true");e.setAttribute("r",l.className);e.setAttribute("d",l.day)}e.setAttribute("m",i[0]+"-"+i[1]);e.onmouseover=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r")+" hover":"spanHover"};e.onmouseout=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r"):"spanOut"};var n=false;l=b.getFullYear();var v=b.getMonth();b.getDate();var q=new Date,t=q.getFullYear(),u=q.getMonth();q=q.getDate();if(t>l)n=true;else if(t==l)if(u>v)n=true;else if(u==v)if(q>
o)n=true;if(c.endTime){var m=c.endTime.split("-");if(m.length>0)if(parseInt(m[0])<b.getFullYear())n=true;else if(parseInt(m[0])==b.getFullYear())if(parseInt(m[1],10)<b.getMonth()+1)n=true;else if(parseInt(m[1],10)==b.getMonth()+1)if(parseInt(m[2],10)<o)n=true}if(c.startTime){m=c.startTime.split("-");if(m.length>0)if(parseInt(m[0])>b.getFullYear())n=true;else if(parseInt(m[0])==b.getFullYear())if(parseInt(m[1],10)>b.getMonth()+1)n=true;else if(parseInt(m[1],10)==b.getMonth()+1)if(parseInt(m[2],10)>=
o)n=true}if(n&&!c.showPast){e.className="spanOver";if(e.innerHTML=="")e.innerHTML=e.getAttribute("d");e.onmouseover=e.onmouseout=function(){if(this.getAttribute("s")!="true")this.className="spanOver"};e.onclick=null}else e.onclick=function(H){var D=this.getAttribute("m"),y=this.getAttribute("d")?this.getAttribute("d"):this.innerHTML;c._lastTime=D+"-"+y;if(parseInt(y,10)<=9)c._lastTime=D+"-0"+y;if(c.inputElem)c.inputElem.value=c._lastTime;E(function(){c.fn&&c.fn(c._lastTime)});fish.stopBubble(H)};
if(t==l&&u==v&&q==o){e.innerHTML="";e.className="spanDay";e.setAttribute("d",o);e.setAttribute("s","true");e.setAttribute("r",e.className)}if(t==l&&u==v&&q+1==o){e.innerHTML="";e.className="spanTomo";e.setAttribute("s","true");e.setAttribute("d",o);e.setAttribute("r",e.className)}if(c._lastTime!=null){n=c._lastTime.split("-")[0];t=c._lastTime.split("-")[1];u=c._lastTime.split("-")[2];if(I(new Date(n,t-1,u),new Date(l,v,o),c)){e.className=e.getAttribute("s")=="true"?e.getAttribute("r")+" clickDate":
"clickDate";e.onmouseout=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r")+" clickDate":"clickDate"}}}}}d.setAttribute("inited","true")}function E(a){C.calElem.style.display="none";a&&a()}function F(a){var c={css:"",time:"",open:false,startTime:"",endTime:"",inputElem:this[0],showPast:false,fn:null,calElem:null,_lastTime:null,_addNum:0};fish.lang.extend(c,a||{});B(c,c.open)}function I(a,c,d){var b=new Date;if(d.startTime){b=d.startTime;if(typeof b!="string")b=new Date;
else{b=b.replace(/-/g,"/");b=new Date(Date.parse(b))}}else b=new Date(b.getFullYear(),b.getMonth(),b.getDate());if(a-c===0)if(d.showPast)return true;else if(a-b>=0)return true;return false}function G(a,c,d){var b={specialDate:[{date:"2011-01-01",name:"\u5143\u65e6",className:"yuandan"},{date:"2011-12-25",name:"\u5723\u8bde\u8282",className:"\u5723\u8bde"},{date:"2012-01-01",name:"\u5143\u65e6",className:"yuandan"},{date:"2012-02-22",name:"\u9664\u5915",className:"chuxi"},{date:"2012-04-04",name:"\u6e05\u660e",
className:"qingming"},{date:"2012-05-01",name:"\u52b3\u52a8\u8282",className:"wuyi"},{date:"2012-06-01",name:"\u513f\u7ae5\u8282",className:"liuyi"},{date:"2012-06-23",name:"\u7aef\u5348",className:"duanwu"},{date:"2012-08-23",name:"qixi",className:"qixi"},{date:"2012-09-30",name:"\u4e2d\u79cb",className:"zhongqiu"},{date:"2012-10-01",name:"\u56fd\u5e86",className:"guoqing"},{date:"2012-12-25",name:"\u5723\u8bde",className:"shendan"},{date:"2013-01-01",name:"\u5143\u65e6",className:"yuandan"}]};a:{a=
new Date(a,c-1,d);if(b){b=b.specialDate;var f,g;d=-1;d=0;for(f=b.length;d<f;d++){c=b[d];g=c.date;var i=g=new Date(g.replace(/-/g,"/")),h=a;i.getFullYear();i.getMonth();i.getDate();h.getFullYear();h.getMonth();h.getDate();var j=false;if(i.getTime()==h.getTime())j=true;if(j){d={};d.name=c.name;d.className=c.className;d.day=g.getDate()+"";a=d;break a}}}a=-1}return a}var C,x;F.close=E;fish.extend({mCal:F,preventInput:A,recoverInput:function(a){fish.all(a?a:this).each(function(c){if(c.getAttribute("_preventInput_")){c.style.imeMode=
"";c.onkeydown=c.oncontextmenu=c.onselectstart=null;c.setAttribute("_preventInput_","")}})},parseTime:w,parseDate:function(a,c){var d=w(a,c,true);return new Date(parseInt(d.y,10),parseInt(d.m,10)-1,parseInt(d.d,10),parseInt(d.h,10),parseInt(d.mi,10),parseInt(d.s,10))}})})();
