AutoComplete=function(d){var a={input:null,popup:null,className:"listbox_se",current:-1,defaultValue:"",parentDoc:null,firstSelected:true,userIe6bug:true,finshFun:function(){}};fish.lang.extend(a,d);fish.lang.extend(this,a);this.init(a)};
AutoComplete.prototype={init:function(d){var a=this;a.input=document.getElementById(d.inputId);a.popup=document.createElement("div");if(!a.isNullOrEmpty(d.className))a.popup.className=d.className;a.parentDoc=a.isNullOrEmpty(d.parentId)?document.body:document.getElementById(d.parentId);a.parentDoc.appendChild(this.popup);fish.on("click",function(b){for(b=fish.getTarget(b);b!==null;){if(b===a)return;b=b.parentNode}fish.one(a.popup).addClass("none")},document);if(d.firstSelected===false)a.firstSelected=
false;if(d.userIe6bug===true)this.userIe6bug=true;if(typeof d.finshFun==="function")a.finshFun=d.finshFun},isNullOrEmpty:function(d){return d!=null&&fish.trim(d).length>0?false:true},hide:function(){fish.one(this.popup).addClass("none");this.popup.innerHTML=""},show:function(d,a){this.popup.innerHTML="";if(this.userIe6bug===true)this.popup.innerHTML='<iframe scrolling="no" frameborder="0" class="iframeie6"></iframe>';var b=d.HotelChain,g=d.HotelList,e=null,h=this.input.value.toString();this.defaultValue=
h;var i=document.createElement("dl"),c=document.createElement("dt");switch(a){case "city":e=d;c.innerHTML="\u8f93\u5165\u4e2d\u6587/\u62fc\u97f3/\u6216\u2191\u2193\u952e\u9009\u62e9";break;case "hotelname":if(b.length&&g.length)e=[b].concat(g);else if(b.length&&!g.length)e=[b];else if(!b.length&&g.length)e=g;else return;c.innerHTML=d.Title;break;case "position":e=d.HotelLocationList;c.innerHTML=d.Title;break;default:e=d;c.innerHTML="\u8f93\u5165\u4e2d\u6587/\u62fc\u97f3\u6216\u2191\u2193\u952e\u9009\u62e9"}i.appendChild(c);
var f,k;g=d.HotelNameKeys;for(c=0;c<e.length;c++){f=e[c][1];b=document.createElement("dd");b.title=f;b.index=c;switch(a){case "city":f=e[c][1];k=e[c][3];b.title=f;b.setAttribute("cid",e[c][5]);b.setAttribute("ctype",e[c][2]);b.innerHTML='<span class="citypy">'+k+'</span><span class="cityhy">'+f+"</span>";break;case "hotelname":try{var j=RegExp(g,"gi")}catch(l){}b.setAttribute("cid",e[c][0]);b.setAttribute("ctype",e[c][2]);if(c==e.length-1&&e.length>10){f="\u66f4\u591a\u542b\u201c"+g+"\u201d\u7684\u9152\u5e97";
g=g.replace(j,'<span class="yellow">'+g+"</span>");k="\u66f4\u591a\u542b\u201c"+g+"\u201d\u7684\u9152\u5e97";b.title=f;b.innerHTML=k}else{f=f.replace(j,'<span class="yellow">'+h+"</span>");b.innerHTML=f}break;case "position":b.setAttribute("cid",e[c][0]);b.setAttribute("ctype",e[c][2]);try{j=RegExp(h,"gi")}catch(m){}f=f.replace(j,'<span class="yellow">'+h+"</span>");b.innerHTML='<span class="cityhyword">'+f+"</span>";break;default:try{j=RegExp(h,"gi")}catch(n){}f=f.replace(j,'<span class="yellow">'+
h+"</span>");b.innerHTML='<span class="cityhyword">'+f+"</span>"}i.appendChild(b)}this.popup.appendChild(i);fish.one(this.popup).removeClass("none");this.parentDoc.style.display="block";this.initEvent(a)},initEvent:function(d){var a=this,b=a.popup.getElementsByTagName("dd");if(a.firstSelected)if(b.length>0)b[0].className="on";a.current=-1;var g=function(){for(var c=0;c<b.length;c++)b[c].className=""},e=function(c){a.input.value=c},h=function(c){switch(c){case "hotelname":if(a.current<=-1){a.input.setAttribute("cid",
0);a.input.setAttribute("ctype",2)}else{a.input.setAttribute("ctype",b[a.current].getAttribute("ctype"));a.input.setAttribute("cid",b[a.current].getAttribute("cid"))}break;default:if(a.current<=-1){a.input.setAttribute("ctype",0);a.input.setAttribute("cid",0)}else{a.input.setAttribute("ctype",b[a.current].getAttribute("ctype"));a.input.setAttribute("cid",b[a.current].getAttribute("cid"))}}};a.input.onkeydown=function(c){c=c||window.event;if(c.keyCode==40){g();if(a.current===b.length)a.current=0;else a.current++;
if(a.current>=b.length){a.current=-1;e(a.defaultValue)}else{b[a.current].className="on";e(b[a.current].title.toString())}h(d);fish.preventDefault(c)}else if(c.keyCode==38){g();if(a.current===-1)a.current=b.length-1;else a.current--;if(a.current<=-1){h(d);a.current=b.length;e(a.defaultValue)}else{b[a.current].className="on";e(b[a.current].title.toString());h(d)}}else if(c.keyCode==13){a.current>-1&&a.current<b.length&&e(b[a.current].title.toString());fish.one(a.popup).addClass("none");a.current=-1}};
for(var i=0;i<b.length;i++){b[i].onmouseover=function(){g();this.className="on";a.current=this.index};b[i].onclick=function(){a.current=-1;e(this.title.toString());fish.one(a.popup).addClass("none");var c=this.getAttribute("ctype"),f=this.getAttribute("cid");c!=undefined&&a.input.setAttribute("ctype",c);f!=undefined&&a.input.setAttribute("cid",f)}}}};AutoComplete.prototype.constructor=AutoComplete;fish.extend({autoComplete:function(d){return new AutoComplete(d)}});
