(function(){function K(a){a.single_cal_width=(a.eachWidth+3)*7;a.cal_height=(a.eachHeight+3)*6+4;a.tol_cal_width=(a.single_cal_width+10)*a.monthNum-10}function y(a,b){var c,e;K(a);var g=a.inputElem,f,i;if(g){b&&a.beforeOpen&&a.beforeOpen.call(a);if((c=g.getAttribute("data-mcalId"))==null){g.setAttribute("data-mcalId",++F);a.mCalId=F;var j=document.createElement("div"),l=document.createElement("iframe"),s=document.createElement("div");f=document.createElement("div");var p="",k="",h="<div class = 'top'>",
u="";a.calElem=j;j.id="mCalendar"+a.mCalId;j.onselectstart=function(){return false};document.body.insertBefore(j,document.body.firstChild);l.className="if";l.src="http://img1.40017.cn/cn/new_ui/public/images/png_cover.png";j.appendChild(l);s.className="date";j.appendChild(s);s.appendChild(f);f.className="top";f=0;for(i=a.monthNum;f<i;f++){if(f==0&&i==1){p=z(a,"one");k=A(a,"first")}else if(f==0){p=z(a,"first");k=A(a,"first")}else if(f==i-1){p=z(a,"last");k=A(a,"last")}else{p=z(a,"mcal"+f,f);k=A(a,
"mcal"+f)}h+=p;u+=k}h+="</div>";s.innerHTML=h+u;a.top_height=27;a.th_height=fish.one("th",a.calElem).height();a.cal_head_height=a.top_height+a.th_height;fish.one(j).css("width:"+(a.tol_cal_width+4)+"px;height:"+(a.cal_height+a.cal_head_height+4)+"px;");l.style.cssText="width:"+(a.tol_cal_width+4)+"px;height:"+(a.cal_height+a.cal_head_height+4)+"px;";fish.one(s).css("width:"+a.tol_cal_width+"px;");j.className="mCalendar";fish.all(a.calElem).css("display:none;")}if(!a.calElem&&(e=fish.all("#mCalendar"+
c)).length)a.calElem=e[0];fish.dom("#mCalendar"+a.mCalId+" .date_lastSpan").onclick=function(){a._DFirstDrawTime=fish.parseDate(a._DFirstDrawTime,{months:-a.monthNum});C(a)};fish.dom("#mCalendar"+a.mCalId+" .date_nextSpan").onclick=function(){a._DFirstDrawTime=fish.parseDate(a._DFirstDrawTime,{months:a.monthNum});C(a)};if(!g.bindCal){c=g.tagName==="INPUT"?fish.all(g):fish.all();if(a.elem){c[c.length]=a.elem;c.length++;fish.all(c).on("click",function(){y(a,true)})}c[c.length]=fish.dom(".date",a.calElem);
c.length++;fish.all(c).on("focus",function(){y(a,true)});fish.all(c).on("keydown",function(n){var w;if(n&&n.keyCode)w=n.keyCode;else if(n&&n.which)w=n.which;w===9&&B(a)});fish.all(c).on("change",function(){var n=fish.trim(this.value);n=fish.parseTime(n);this.value=a.showPast?n:fish.parseDate(n).getTime()<fish.parseDate(a.startTime).getTime()?a.startTime:n});switch(a.showType){case "pop":break;case "static":break;default:fish.all(a.calElem).effect({elem:c,type:"click",interShow:false,outerHide:false,
outerFn:function(){B(a)}})}g.bindCal=true}if(a.calElem){a.calElem.className="mCalendar"+(a.css?" "+a.css:"");a.now=g.value?g.value:fish.parseTime(a.now);a._DFirstDrawTime=fish.parseDate(g.value);a._DFirstDrawTime.setDate("1");c=parseInt(a.now.split("-")[1],10);a._addNum=c&&!(c%2)?-1:0;if(b){C(a);switch(a.showType){case "pop":fish.all(a.calElem).css("position: static");fish.require("mPop",function(){if(fish.all(a.calElem).getCss("display")!=="block"){fish.all(a.calElem).css("display:block;");fish.mPop({content:a.calElem,
afterClose:function(){fish.all(a.calElem).css("display:none;")}})}});break;case "static":fish.all(a.calElem).css("position: relative;display:block");fish.one(a.inputElem).css("display:block").html("top",a.calElem);break;default:c=fish.one(g).offset();g=fish.one(g).height();e=fish.one(window).width();e=e-c.left>=a.tol_cal_width+20?c.left:c.left-20-(a.tol_cal_width-(e-c.left));fish.all(a.calElem).css("top:"+(c.top+g)+"px; left:"+e+"px;");fish.all(a.calElem).css("display:block;")}}}}}function z(a,b,
c){var e="<div class = 'floatL' style = 'width:"+a.single_cal_width+"px;'>";if(b=="one")return e+"<h4 class='lastText mCalTitleFir'  style = 'width:"+a.single_cal_width+"px;'><span class='lastMonthBg date_lastSpan'><span class='lastMonth'></span></span><span class='nextMonthBg date_nextSpan'><span class='nextMonth' ></span></span><span class=date_title>....\u5e74..\u6708</span></h4></div>";else if(b=="first")return e+"<h4 class='lastText  mCalTitleFir'  style = 'width:"+a.single_cal_width+"px;'><span class='lastMonthBg date_lastSpan'><span class='lastMonth'></span></span><span class=date_title>....\u5e74..\u6708</span></h4></div>";
else if(b=="last"){e="<div class = 'floatL' style = 'width:"+a.single_cal_width+"px;margin-left:10px'>";return e+"<h4 class='nextText  mCalTitleLast' style = 'width:"+a.single_cal_width+"px;'><span class='nextMonthBg date_nextSpan' ><span class='nextMonth' ></span></span><span class=date_title>....\u5e74..\u6708</span></h4></div>"}else{e="<div class = 'floatL' style = 'width:"+a.single_cal_width+"px;margin-left:10px'>";return e+"<h4 class='normalText mCalTitleMid"+c+"' style = 'width:"+a.single_cal_width+
"px;'><span class='nomalMonthBg'></span><span class=date_title>....\u5e74..\u6708</span></h4></div>"}}function A(a,b){var c="";if(b=="first"){c="<div class = 'contentTime1 contentTime clearfix'>";c+="<table cellspacing='0' cellpadding='0' class='tbl_lastMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg' >1</i>"}else if(b=="last"){c="<div class = 'contentTime2 contentTime clearfix'>";
c+="<table cellspacing='0' cellpadding='0' class='tbl_nextMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg'>12</i>"}else{c="<div class = 'contentTimeMiddle contentTime clearfix'>";c+="<table cellspacing='0' cellpadding='0' class="+b+" border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg' >1</i>"}c+=
"</div>";return c}function v(a,b,c,e,g,f){var i=fish.dom(a),j=i.parentNode,l=fish.dom(g+" .date_title"),s=fish.all("td",i),p=i.parentNode.getElementsByTagName("i"),k=e.getFullYear(),h=e.getMonth()+1,u=e.getDay(),n=new Date,w=n.getFullYear(),D=n.getMonth()+1;n=n.getDate();var L=0,q=b.ajaxUrl,m;if(p.length>0){if(!f){p[0].innerHTML=parseInt(h,10);fish.all(p[0]).removeClass("loadingbg");s.removeClass("none")}fish.one(p[0]).css("height:"+(b.cal_height+b.cal_head_height)+"px;line-height:"+(b.cal_height+
b.cal_head_height)+"px;width:"+b.single_cal_width+"px");fish.one(p[0]).removeClass("none")}l.innerHTML=k+"\u5e74"+h+"\u6708";fish.one(j).css("height:"+(b.cal_height+b.th_height)+"px;width:"+b.single_cal_width+"px");fish.all("th",i).css("width:"+(b.eachWidth+3)+"px");if(f){p[0].innerHTML=parseInt(h,10);fish.all(p[0]).removeClass("loadingbg");s.removeClass("none")}else if(b.processDataFn&&b.dateTempleteFn&&q&&typeof b.processDataFn=="function"){f=typeof q==="function"?q():q;f=f.replace("{year}",k);
f=f.replace("{month}",h);p[0].innerHTML="";fish.all(p[0]).addClass("loadingbg");s.addClass("none");if(b.ajaxObj[c]){b.ajaxObj[c].abort();b.ajaxObj[c]=null}b.ajaxObj[c]=fish.ajax({url:f,type:"json",fn:function(x){b.ajaxObj[c]=null;if(x)(x=b.processDataFn(x))?v(a,b,c,e,g,x):v(a,b,c,e,g,[])},err:function(){b.ajaxObj[c]=null;v(a,b,c,e,g,[])}});return}b.isDebug&&e.getDate()!=1&&window.console&&console.error("\u4f20\u5165\u7684DDrawDate\u7684\u5fc5\u987b\u4e3a\u5f53\u6708\u7684\u7b2c\u4e00\u5929\uff01\uff01\uff01");
s=i.getAttribute("inited")=="true";var G;p=M(e);if(u!=7)p+=u;var H;j=true;if(s){H=fish.all("tr",i);tds=fish.all("td",i);items=fish.all(".itemWrap",i)}for(l=1;l<=42;l++){q=l-u;if(l%7==1)G=s?H[parseInt(l%7,10)]:i.insertRow(i.rows.length);var o;if(s){m=tds[l-1];d=items[l-1];o=fish.dom(".dateWrap",d);o.className="dateWrap";d.className="itemWrap"}else{m=G.insertCell(l%7-1);m.innerHTML="";var d=document.createElement("div");o=document.createElement("span");var r=document.createElement("div");o.className=
"dateWrap";d.className="itemWrap";r.className="useWrap";d.style.cssText="height:"+b.eachHeight+"px;width:"+b.eachWidth+"px;float:left;display:inline;overflow:hidden;position:relative;";m.appendChild(d);d.appendChild(o);d.appendChild(r)}if(u!=7&&l<=u||l>p){o.innerHTML="";fish.one(".useWrap",d).html("");m.className="td02";d.className="spanOut itemWrap";d.onmouseover=d.onmouseout=d.onclick=null}else{m.className="td01";m=N(k,h,q);if(m==-1){o.innerHTML=q;d.className+=" spanOut";d.setAttribute("s","false");
d.setAttribute("d",q)}else{o.innerHTML="";o.className=o.className+" "+m.className;d.className+=" spanOut";d.setAttribute("s","true");d.setAttribute("r",d.className);d.setAttribute("d",m.day)}m=fish.one(".useWrap",d);if(b.dateTempleteFn&&typeof b.dateTempleteFn=="function"&&f){j=b.dateTempleteFn(k,h,q,f[L++]);j!==false?m.html(j):m.html("")}h<10?d.setAttribute("m",k+"-0"+h):d.setAttribute("m",k+"-"+h);if(j===false&&m&&m.length){fish.one(m[0].parentNode)[0].className="itemWrap spanOver";d.onmouseover=
d.onmouseout=null}else{d.onmouseover=function(){if(this.getAttribute("s")=="true")this.className=this.getAttribute("r")+" hover";else fish.one(this).addClass("spanHover")};d.onmouseout=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r"):"itemWrap spanOut"}}r=false;if(w>k)r=true;else if(w==k)if(D>h)r=true;else if(D==h)if(n>q)r=true;if(b.endTime){var t=b.endTime.split("-");if(t.length>0)if(parseInt(t[0])<k)r=true;else if(parseInt(t[0])==k)if(parseInt(t[1],10)<h)r=true;else if(parseInt(t[1],
10)==h)if(parseInt(t[2],10)<q)r=true}if(b.startTime){t=b.startTime.split("-");if(t.length>0)if(parseInt(t[0],10)>k)r=true;else if(parseInt(t[0])==k)if(parseInt(t[1],10)>h)r=true;else if(parseInt(t[1],10)==h)if(parseInt(t[2],10)>parseInt(q,10))r=true}if(r&&!b.showPast){d.className="itemWrap spanOver";o.className="dateWrap";if(o.innerHTML=="")o.innerHTML=d.getAttribute("d");d.onmouseover=d.onmouseout=d.onclick=null}else d.onclick=j!==false&&m&&m.length?function(){var x=this,I=this.getAttribute("m"),
E=this.getAttribute("d")?this.getAttribute("d"):this.innerHTML;b.now=I+"-"+E;if(parseInt(E,10)<=9)b.now=I+"-0"+E;if(b.inputElem.tagName==="INPUT"){b.inputElem.value=b.now;b.inputElem&&b.showDay&&O(b.inputElem,b.now,b)}B(b,function(){setTimeout(function(){b.fn&&b.fn.call(b,b.now,x)})})}:null;if(w==k&&D==h&&n==q){o.innerHTML="";o.className="spanDay dateWrap";d.setAttribute("d",q);d.setAttribute("s","true");d.setAttribute("r",d.className)}if(fish.parseTime(k+"-"+h+"-"+q)==fish.parseTime(new Date,{days:1})){o.innerHTML=
"";o.className="spanTomo dateWrap";d.setAttribute("s","true");d.setAttribute("d",q);d.setAttribute("r",d.className)}if(b.now!=null){o=b.now.split("-")[0];m=b.now.split("-")[1];r=b.now.split("-")[2];if(P(new Date(o,m,r),new Date(k,h,q),b)){d.className=d.getAttribute("s")=="true"?d.getAttribute("r")+" clickDate":"clickDate itemWrap";d.onmouseout=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r")+" clickDate":"clickDate itemWrap"}}}d.className+=" dateWrap"}}i.setAttribute("inited",
"true")}function B(a,b){switch(a.showType){case "pop":fish.require("mPop",function(){fish.mPop.close()});break;case "static":break;default:a.calElem.style.display="none"}b&&b()}function J(a){a=a||{};var b={css:"",open:false,startTime:fish.parseTime(new Date),endTime:"",inputElem:this[0],showPast:false,fn:null,calElem:null,now:fish.parseTime(new Date),beforeOpen:function(){},fontSize:12,_DFirstDrawTime:null,eachHeight:30,eachWidth:30,eachCalMargin:10,monthNum:2,showDay:false,isAjax:false,ajaxFn:false};
b.ajaxObj=[];for(var c=a.monthNum;c--;)b.ajaxObj[c]=null;if(b.inputElem&&b.inputElem.getAttribute("data-mcalid")!=null)b.mCalId=b.inputElem.getAttribute("data-mcalid");fish.lang.extend(b,a);y(b,b.open);return{setAjaxUrl:function(e){b.ajaxUrl=e}}}function P(a,b,c){var e=fish.parseDate(c.startTime);if(a-b===0)if(c.showPast)return true;else if(a-e>=0)return true;return false}function N(a,b,c){var e={specialDate:[{date:"2011-01-01",name:"\u5143\u65e6",className:"yuandan"},{date:"2011-12-25",name:"\u5723\u8bde\u8282",
className:"\u5723\u8bde"},{date:"2012-01-01",name:"\u5143\u65e6",className:"yuandan"},{date:"2012-02-22",name:"\u9664\u5915",className:"chuxi"},{date:"2012-04-04",name:"\u6e05\u660e",className:"qingming"},{date:"2012-05-01",name:"\u52b3\u52a8\u8282",className:"wuyi"},{date:"2012-06-01",name:"\u513f\u7ae5\u8282",className:"liuyi"},{date:"2012-06-23",name:"\u7aef\u5348",className:"duanwu"},{date:"2012-08-23",name:"qixi",className:"qixi"},{date:"2012-09-30",name:"\u4e2d\u79cb",className:"zhongqiu"},
{date:"2012-10-01",name:"\u56fd\u5e86",className:"guoqing"},{date:"2012-12-25",name:"\u5723\u8bde",className:"shendan"},{date:"2013-01-01",name:"\u5143\u65e6",className:"yuandan"}]};a:{a=new Date(a,b-1,c);if(e){e=e.specialDate;var g,f;c=-1;c=0;for(g=e.length;c<g;c++){b=e[c];f=b.date;var i=f=new Date(f.replace(/-/g,"/")),j=a;i.getFullYear();i.getMonth();i.getDate();j.getFullYear();j.getMonth();j.getDate();var l=false;if(i.getTime()==j.getTime())l=true;if(l){c={};c.name=b.name;c.className=b.className;
c.day=f.getDate()+"";a=c;break a}}}a=-1}return a}function C(a){var b=a._DFirstDrawTime,c,e;c=v.markCount=0;for(e=a.monthNum;c<e;c++){if(c==0)v("#mCalendar"+a.mCalId+" .tbl_lastMonth",a,c,b,"#mCalendar"+a.mCalId+" .mCalTitleFir");else c==e-1?v("#mCalendar"+a.mCalId+" .tbl_nextMonth",a,c,b,"#mCalendar"+a.mCalId+" .mCalTitleLast"):v("#mCalendar"+a.mCalId+" .mcal"+c,a,c,b,"#mCalendar"+a.mCalId+" .mCalTitleMid"+c);b=fish.parseDate(b,{months:1});v.markCount++}}function M(a){a=new Date(a);a.setMonth(a.getMonth()+
1);a.setDate(0);return a.getDate()}function O(a,b,c){b=fish.parseDate(b).getDay();var e=fish.one(".mCalendar"+c.mCalId);a=fish.one(a);if(e.length==0){e=fish.one(document.createElement("div"));e.addClass("dayWrap");e.addClass("mCalendar"+c.mCalId);e.css("height:"+a.height()+"px;line-height:"+a.height()+"px;left:"+(a.offset().left+a.width()-52)+"px;top:"+a.offset().top+"px;font-size:"+Q(a)+";");document.body.appendChild(e[0]);e.on("click",function(){y(c,true)})}switch(b){case 1:b="\u4e00";break;case 2:b=
"\u4e8c";break;case 3:b="\u4e09";break;case 4:b="\u56db";break;case 5:b="\u4e94";break;case 6:b="\u516d";break;case 0:b="\u65e5"}e.html("\u661f\u671f"+b)}function Q(a){try{return fish.one(a).getCss("font-size")}catch(b){return 12}}var F=0;J.close=B;fish.extend({mCal:J,preventInput:function(a){fish.all(a?a:this).each(function(b){if(!b.getAttribute("_preventInput_")){b.style.imeMode="disabled";b.onkeydown=function(c){fish.preventDefault(c)};b.oncontextmenu=function(){return false};b.onselectstart=function(){return false};
b.setAttribute("_preventInput_","true")}})},recoverInput:function(a){fish.all(a?a:this).each(function(b){if(b.getAttribute("_preventInput_")){b.style.imeMode="";b.onkeydown=b.oncontextmenu=b.onselectstart=null;b.setAttribute("_preventInput_","")}})}})})();
