(function(){function K(a,b){var c=false,d;a.forEach(function(g,o){if(!c)if(g.dInputElem==b){c=true;d=o}});return c?d:false}function D(a){var b={dom:null,pass:false,type:"",fail:"\u9519\u8bef"};fish.lang.extend(b,a);fish.lang.extend(this,b);this.init()}function E(a,b,c){c=c||10;b=b||"right";var d=fish.one(a),g=d.offset();a=d.width();var o=d.height(),i=g.top;g=g.left;d=d.attr("data-showType")=="static"?"position:static;":"position:absolute;";c=parseInt(c,10);if(b=="right")g+=a+c;else if(b=="bottom")i+=
o+c;d+="left:"+g+"px;top:"+i+"px;";return d}function F(a,b){var c={elem:a,type:[],all:[],pass:false,fail:function(){},success:function(){},isDebug:false,position:"right",gap:10,__tipLocArr:[]};fish.lang.extend(c,b);fish.lang.extend(this,c);if(c.isDebug)p.isDebug=true;this.init()}var y=function(a,b,c){function d(f,e){for(var h in f){var j=f[h];if(!~(""+j).indexOf("-")&&k[j]!==c)return e=="pfx"?j:true}return false}function g(f,e,h){var j=f.charAt(0).toUpperCase()+f.slice(1),q=(f+" "+G.join(j+" ")+j).split(" ");
if(typeof e==="string"||typeof e==="undefined")return d(q,e);else{q=(f+" "+H.join(j+" ")+j).split(" ");a:{f=q;for(var s in f){j=e[f[s]];if(j!==c){if(h===false){e=f[s];break a}if(typeof j==="function"){e=j.bind(h||e);break a}e=j;break a}}e=false}return e}}function o(){i.input=function(f){for(var e=0,h=f.length;e<h;e++)v[f[e]]=!!(f[e]in m);if(v.list)v.list=!!(b.createElement("datalist")&&a.HTMLDataListElement);return v}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));
i.inputtypes=function(f){for(var e=0,h,j,q=f.length;e<q;e++){m.setAttribute("type",j=f[e]);if(h=m.type!=="text"){m.value=r;m.style.cssText="position:absolute;visibility:hidden;";if(/^range$/.test(j)&&m.style.WebkitAppearance!==c){l.appendChild(m);h=b.defaultView;h=h.getComputedStyle&&h.getComputedStyle(m,null).WebkitAppearance!=="textfield"&&m.offsetHeight!==0;l.removeChild(m)}else/^(search|tel)$/.test(j)||(h=/^(url|email)$/.test(j)?m.checkValidity&&m.checkValidity()===false:m.value!=r)}I[f[e]]=!!h}return I}("search tel url email datetime date month week time datetime-local number range color".split(" "))}
var i={},l=b.documentElement,n=b.createElement("modernizr"),k=n.style,m=b.createElement("input"),r=":)",L=" -webkit- -moz- -o- -ms- ".split(" "),G="Webkit Moz O ms".split(" "),H="Webkit Moz O ms".toLowerCase().split(" ");n={};var I={},v={},J=[],z=J.slice,w,M=function(){var f={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(e,h){h=h||b.createElement(f[e]||"div");e="on"+e;var j=e in h;if(!j){h.setAttribute||(h=b.createElement("div"));if(h.setAttribute&&
h.removeAttribute){h.setAttribute(e,"");j=typeof h[e]==="function";typeof h[e]==="undefined"||(h[e]=c);h.removeAttribute(e)}}return j}}(),A={}.hasOwnProperty,B;B=typeof A!=="undefined"&&typeof A.call!=="undefined"?function(f,e){return A.call(f,e)}:function(f,e){return e in f&&typeof f.constructor.prototype[e]==="undefined"};if(!Function.prototype.bind)Function.prototype.bind=function(f){var e=this;if(typeof e!="function")throw new TypeError;var h=z.call(arguments,1),j=function(){if(this instanceof
j){var q=function(){};q.prototype=e.prototype;q=new q;var s=e.apply(q,h.concat(z.call(arguments)));if(Object(s)===s)return s;return q}else return e.apply(f,h.concat(z.call(arguments)))};return j};for(var C in n)if(B(n,C)){w=C.toLowerCase();i[w]=n[C]();J.push((i[w]?"":"no-")+w)}i.input||o();i.addTest=function(f,e){if(typeof f=="object")for(var h in f)B(f,h)&&i.addTest(h,f[h]);else{f=f.toLowerCase();if(i[f]!==c)return i;e=typeof e=="function"?e():e;if(typeof enableClasses!=="undefined"&&enableClasses)l.className+=
" "+(e?"":"no-")+f;i[f]=e}return i};k.cssText="";n=m=null;i._version="2.6.2";i._prefixes=L;i._domPrefixes=H;i._cssomPrefixes=G;i.hasEvent=M;i.testProp=function(f){return d([f])};i.testAllProps=g;i.testStyles=function(f,e,h,j){var q,s,t=b.createElement("div"),x=b.body,u=x||b.createElement("body");if(parseInt(h,10))for(;h--;){q=b.createElement("div");q.id=j?j[h]:"modernizr"+(h+1);t.appendChild(q)}h=['&#173;<style id="smodernizr">',f,"</style>"].join("");t.id="modernizr";(x?t:u).innerHTML+=h;u.appendChild(t);
if(!x){u.style.background="";u.style.overflow="hidden";s=l.style.overflow;l.style.overflow="hidden";l.appendChild(u)}f=e(t,f);if(x)t.parentNode.removeChild(t);else{u.parentNode.removeChild(u);l.style.overflow=s}return!!f};i.prefixed=function(f,e,h){return e?g(f,e,h):g(f,"pfx")};return i}(this,this.document),p={rule:{isRquire:/.+/,isEnglish:/^[A-Za-z]+$/,isChinese:/^[\u0391-\uFFE5]+$/,isChineseWord:/^[\u4e00-\u9fa5]+$/,isEnOrCn:/^[A-Za-z\u0391-\uFFE5]+$/,isEnOrCnWord:/^[A-Za-z\u4e00-\u9fa5]+$/,isMail:/\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/,
isUrl:/^http[s]?:\/\/[A-Za-z0-9]+\.[A-Za-z0-9]+[\/=\?%\-&_~`@[\]\':+!]*([^<>\"\"])*$/,isCurrency:/^\d+(\.\d+)?$/,isNumber:/^\d+$/,isInt:/^[0-9]{1,30}$/,isDouble:/^[-\+]?\d+(\.\d+)?$/,isUsername:/[0-9a-zA-Z]{3,20}/ig,isPassword:/^(\w){6,20}$/,isQQ:/[1-9][0-9]{4,}/,isYear:/^(19|20)[0-9]{2}$/,isMonth:/^(0?[1-9]|1[0-2])$/,isDay:/^((0?[1-9])|((1|2)[0-9])|30|31)$/,isHour:/^((0?[1-9])|((1|2)[0-3]))$/,isMinute:/^((0?[1-9])|((1|5)[0-9]))$/,isMobile:/^0?(13|14|15|18)[0-9]{9}$/,isZipcode:/^[1-9]\d{5}$/,isIdCard:/(^\d{15}$)|(\d{17}(?:\d|x|X)$)/,
isIP:/^(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])$/,isLimitFile:/^[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/,isLimitImage:/.+\.(jpg|gif|png|bmp)$/i,isLimitWord:/.+\.(doc|rtf)$/i},_tipWrapId:0,getField:function(a){return a},checkField:function(a,b,c,d){var g=true;if(a&&b&&c||d!=""&&d!=undefined&&c!=""&&this.getFieldValue(a)!="")this.checkType(a,b,d)||(g=false);return g},getFieldValue:function(a){return this.trim(this.getField(a).value)},
checkType:function(a,b,c){var d=this.getFieldValue(a),g=this.detectBrowserCanHandle(b),o=this.getValidRegName(b);if(b=="fnValid")if(c)return this.toTest("validFn",c,d,a);else throw"validFn is needed!!!";if(g)return this.browserValid(a,b);else if(o)return this.toTest(d,o);else throw b+":not supported";},browserValid:function(a,b){if(b=="rq")return!a.validity.valueMissing;else if(b=="mail"||b=="url"||b=="number"||b=="month")return!a.validity.typeMismatch;else throw"sorry,the valid component don't support "+
b;},_fieldTypeToValidTypeMapping:{mail:y.inputtypes.email,url:y.inputtypes.url,number:y.inputtypes.number,month:y.inputtypes.month},detectBrowserCanHandle:function(a){return this._fieldTypeToValidTypeMapping[a]},getValidRegName:function(a){return this._fieldTypeToRegMapping[a]},_fieldTypeToRegMapping:{rq:"isRquire",eng:"isEnglish",chn:"isChinese",chnWord:"isChineseWord",enOrCn:"isEnOrCn",enOrCnWord:"isEnOrCnWord",mail:"isMail",url:"isUrl",currency:"isCurrency",number:"isNumber","int":"isInt","double":"isDouble",
username:"isUsername",title:"title",password:"isPassword",qq:"isQQ",year:"isYear",month:"isMonth",hour:"isHour",minute:"isMinute",second:"isMinute",mobile:"isMobile",zip:"isZipcode",idCard:"isIdCard",ip:"isIP",file:"isLimitFile",image:"isLimitImage",word:"isLimitWord"},doCustomfunction:function(a,b,c){return typeof a=="string"?eval(a)(b,c):a(b,c)},toTest:function(a,b,c,d){if(a=="title")return this.testTitle(a);else if(a=="validFn")return this.doCustomfunction(b,c,d);else{if(p.rule[b]==undefined)throw"verity component system error!";
return a.match(p.rule[b])!=null?true:false}},trim:function(a){return a.replace(/(^\s*)|(\s*$)/g,"")},equalTo:function(a,b){return a==b?true:false},testTitle:function(a){a=a.match(/[^ -~]/g)==null?a.length:a.length+a.match(/[^ -~]/g).length;return a<=0||a>200?false:true},checkTip:function(a,b,c,d){var g={},o,i=true,l=this;if(typeof b==="string"){b=fish.trim(b);if(b=="fnValid"&&c){(i=this.checkType(a,b,c))?this.showTip(a,"right","\u9a8c\u8bc1\u901a\u8fc7!",d.position,d.gap,d):this.showTip(a,"error",
a.getAttribute("data-err-fn"),d.position,d.gap,d);return i}o=fish.trim(b)==""?[]:b.split(" ")}g.validArr=o;g=this.getAllConstraintValidation(a,g);if(p.isDebug){console.log("\u9a8c\u8bc1\u5143\u7d20:",a);console.log("\u8ba1\u7b97\u51fa\u7684\u9a8c\u8bc1\u89c4\u5219:"+g.validArr);console.log("\u8ba1\u7b97\u51fa\u7684\u9a8c\u8bc1\u9519\u8bef\u63d0\u793a\u8bed:"+g.errMsgArr)}this.convertToH5InputFormat(a,g.validArr);if(a){g.validArr.forEach(function(n,k){if(i&&!l.checkType(a,n)){i=false;l.showTip(a,"error",
g.errMsgArr[k],d.position,d.gap,d)}});i&&this.showTip(a,"right","\u9a8c\u8bc1\u901a\u8fc7!",d.position,d.gap,d)}return i},getAllConstraintValidation:function(a,b){var c=fish.one(a),d=[],g=[],o=c.attr("required")?"rq":false,i=c.attr("type")=="email"?"mail":false,l=c.attr("type")=="url"?"url":false,n=c.attr("type")=="number"?"number":false,k=c.attr("type")=="month"?"month":false,m=this;d=b.validArr.slice(0);b.validArr.forEach(function(r){m.pushErrMsg(c,r,g)});b.validArr.indexOf("rq")=="-1"&&this.bindRuleAndErrMsg(d,
o,this.pushErrMsg,[c,"rq",g],true);b.validArr.indexOf("mail")=="-1"&&this.bindRuleAndErrMsg(d,i,this.pushErrMsg,[c,"mail",g]);b.validArr.indexOf("url")=="-1"&&this.bindRuleAndErrMsg(d,l,this.pushErrMsg,[c,"url",g]);b.validArr.indexOf("number")=="-1"&&this.bindRuleAndErrMsg(d,n,this.pushErrMsg,[c,"number",g]);b.validArr.indexOf("month")=="-1"&&this.bindRuleAndErrMsg(d,k,this.pushErrMsg,[c,"month",g]);b.validArr=d;b.errMsgArr=g;return b},convertToH5InputFormat:function(a,b){var c=fish.one(a);b.forEach(function(d){if(d==
"rq"&&p._fieldTypeToValidTypeMapping.rq)c.attr("required","required");else if(d=="mail"&&p._fieldTypeToValidTypeMapping.mail)c.attr("type","email");else if(d=="url"&&p._fieldTypeToValidTypeMapping.url)c.attr("type","url");else if(d=="number"&&p._fieldTypeToValidTypeMapping.number)c.attr("type","number");else d=="month"&&p._fieldTypeToValidTypeMapping.month&&c.attr("type","month")})},pushErrMsg:function(a,b,c,d){if(a=a.attr("data-err-"+b))a=fish.trim(a);if(a)d?c.unshift(a):c.push(a);else throw"lack of errMsg"+
b;},bindRuleAndErrMsg:function(a,b,c,d,g){if(b!=false){g?a.unshift(b):a.push(b);c&&typeof c=="function"&&c(d[0],d[1],d[2],g)}},removeTip:function(a){p.showTip(a,"hide")},showTip:function(a,b,c,d,g,o){var i=this.getField(a),l=fish.one(a),n=l.attr("data-tipWrapId"),k=l.attr("data-gap"),m=E(a,d,g);if(k)g=k;m=E(a,d,g);k=fish.one("."+n);var r=k[0];if(r){k=fish.one(r);k.removeClass("error right");k.html("remove")}p._tipWrapId++;n="no"+p._tipWrapId;r=document.createElement("span");k=fish.one(r);k.addClass(n);
l.attr("data-tipWrapId",n);if(o){l=o.__tipLocArr;n=K(l,a);l[n].uTip=k;if(p.isDebug&&k.length==0){console.trace();throw"tipElem not finded";}l[n].position=d;l[n].gap=g}else if(p.isDebug){console.log("----------------------");console.log(arguments)}k.css(m);switch(b){case "error":r.innerHTML=c;k.addClass("error");i.parentNode.insertBefore(r,i.nextSibling);break;case "right":r.innerHTML="";k.addClass("right");i.parentNode.insertBefore(r,i.nextSibling)}}};D.prototype={init:function(){this.dom.nodeName.toLowerCase();
var a=this,b=fish.one(this.dom);b.on("change",function(){a.doValid()});try{b.on("invalid",function(d){fish.preventDefault(d)})}catch(c){}},doValid:function(){if(this.param.isDestroy)return true;var a=p.checkTip(this.dom,this.type,null,this.param),b;if(fish.one(this.dom).hasClass("verifyIgnore")){p.removeTip(this.dom);return true}if(a&&this.fn){b=p.checkTip(this.dom,"fnValid",this.fn,this.param);this.pass=a&&b}else this.pass=a;return this.pass}};F.prototype={init:function(){var a=this;this.elem.each(function(b,
c){var d=fish.one(this).attr("vType"),g=fish.one(this).attr("vMsg"),o=eval(fish.one(this).attr("vFn"));a.all[c]=new D({dom:b,type:d,fail:g,fn:o,param:a});a.isDebug&&console.log("valid is inited",this);a.__tipLocArr[c]={};a.__tipLocArr[c].dInputElem=this;a.__tipLocArr[c].gap=a.gap;a.__tipLocArr[c].position=a.position})},check:function(){for(var a=true,b=0;b<this.all.length;b++)this.all[b].doValid()||(a=false);return a},isIgnoreValid:function(a,b){var c=fish.one(b);a?c.addClass("verifyIgnore"):c.removeClass("verifyIgnore")},
destroy:function(){this.isDestroy=true;this.__tipLocArr.forEach(function(a){if(a.uTip&&a.uTip.length>0){try{a.uTip.html("remove")}catch(b){}a.uTip=false}})},resetAllTipLoc:function(){this.__tipLocArr.forEach(function(a){var b=fish.one(a.dInputElem),c=b.offset(),d=c.left;c=c.top;a.position=a.position||"right";a.gap=parseInt(a.gap);if(a.position=="right")d+=a.gap+b.width();else c+=a.gap+b.height();a.uTip&&a.uTip.length>0&&a.uTip.css("left:"+d+"px;top:"+c+"px;")});if(this.isDebug){console.dir(this.elem);
console.dir(this.__tipLocArr)}}};fish.extend({verify:function(a){return new F(this,a)}})})();
