(function(){fish.extend({autoComplete:function(c){function I(){if(!J){var a=document.createElement("iframe");a.id="mNotice-backdrop";fish.one(i).html("top",a);fish.one(a).css("position:absolute;border:none;filter:alpha(opacity=0);opacity:0;z-index:-1");J=a}a=fish.one(i).width();var b=fish.one(i).height();fish.all(J).css("width:"+a+"px;height:"+b+"px")}function ba(a){y&&clearTimeout(y);y=setTimeout(function(){if(h.ajaxObj)try{h.ajaxObj.abort()}catch(b){}h.ajaxObj=fish.ajax({url:a,type:K,fn:function(d){U(d);
d=V(d);h.origin=e.val();if(d&&d.length){e.setTitle(L);M(d)}else{N&&M();d="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(e.val());e.setTitle(d)}I()}});y=null},200)}function M(a,b){a&&A&&A.call(e,a);p=a;var d;W(j);if(a&&a.length){for(n=0;n<a.length;n++){row=j.insertRow(-1);cell=row.insertCell(-1);d=O.call(row,a[n],n);row.className=l;if(d)row.className+=" "+t;d=B.call(row,a[n],n);if(d===false)j.deleteRow(-1);else cell.innerHTML=P.call(row,a[n],n)?z(d,b):d}if(j.index!==-1){for(d=fish.all("."+l,
j);d[j.index]&&!fish.one(d[j.index]).hasClass(t);)j.index++;if(d[j.index])fish.one(d[j.index]).addClass(q);else j.index=-1}}}function X(a){var b=[],d,f,g,k,m,u,o,r,C,Y;r=w.length;for(o=0;o<r;o++){d=w[o];f=d.match;Y=f.length;k=-1;for(C=0;C<Y;C++){g=f[C];if(Q)g=g.toLowerCase();if((m=g.indexOf(a))>-1&&(k===-1||m<k)){k=m;u=g}}if(k>-1){D&&D(d,u,k);b[b.length]=d}}if(b.length)b.matchLength=a.length;else{a=a.substr(0,a.length-1);if(a!=="")b=X(a);b.matchFalid=true}return b}function Z(a){var b;if(Q)a=a.toLowerCase();
b=X(a);h.origin=a;if(b.length){E&&b.sort(E);F&&b.splice(F,b.length);if(b.matchFalid){var d="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(a);e.setTitle(d)}else e.setTitle(L);M(b,a.substr(0,b.matchLength))}else{a="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(a);e.setTitle(a);W(j)}I()}function z(a,b){if(ca){var d=b?b:e.val(),f=RegExp(d,"g"+(Q?"i":""));return a.replace(/(>|^)([^>^<]+)(<|$)/g,function(g){return g.replace(f,function(k){return'<span class="'+$+'">'+k+"</span>"})})}else return a}
function aa(a,b,d){if(a&&a[0].nodeType===1&&b&&b[0].nodeType===1){var f=fish.one(window).width();fish.one(window).height();var g=b.width(),k=b.height(),m=a.width();a.height();b=b.offset();fish.one(document).scrollTop();var u=fish.one(document).scrollLeft(),o;if(o=d){var r;a:{for(r in d){r=false;break a}r=true}o=!r}if(o){d.x=typeof d.x==="number"?d.x:0;d.y=typeof d.y==="number"?d.y:0}else d={x:0,y:0};b.left-u>f-(b.left-u)&&f-(b.left-u)<m?a.css("left:"+(b.left+g-m-d.x)+"px"):a.css("left:"+(b.left+d.x)+
"px");a.css("top:"+(b.top+k+d.y)+"px")}else throw Error("\u9700\u8981\u6307\u5b9a\u8f93\u5165\u57df\u548c/\u6216\u53ca\u5176\u5f39\u6846\uff01");}function W(a){a.index=da;for(var b=fish.all("."+l,a).length;b-- >0;)a.deleteRow(-1)}var h,R=fish.guid(),i,S,w=[],p={},G={x:0,y:0},L="\u8f93\u5165\u4e2d\u6587/\u62fc\u97f3/\u2191\u2193\u952e\u9009\u62e9",e={},D=null,E=null,H,ca=true,F=10,da=0,N=false,x="",K="get",Q=true,A,V=function(){},B=function(){},s=function(){},O=function(){},U=function(){},P=function(){return true},
v=false,j,J,l="autofill_item",t="enableListRow",q="autofill_hover",$="autofill_hili",T="autofill_empty";h=this;if(!h[0])throw Error("autoComplete init faild, fish obj was null when exec fish.all('...').autoComplete()");fish.one("body").html("top",'<div id="autoComplete-'+R+'" class="autofill_wrap"><table class="autofill_tray" cellpadding="0" cellspacing="0"><tr class="autofill_title"><th class="autofill_hd"><span class="autofill_hd_inner"></span></th></tr></table><span class="autofill_close"></span></div>');
i=fish.one("#autoComplete-"+R);S=fish.one(".autofill_hd_inner",i[0]);j=fish.dom(".autofill_tray",i[0]);G.x=c.offsetX!==undefined?c.offsetX:0;G.y=c.offsetY!==undefined?c.offsetY:0;if(typeof c.processAjaxDataFn==="function")V=c.processAjaxDataFn;if(typeof c.itemPrintFn==="function")B=c.itemPrintFn;if(typeof c.template==="string"&&fish.trim(c.template).length)R=c.template;if(typeof c.title==="string"&&fish.trim(c.title).length){L=c.title;S.html(c.title)}typeof c.theme==="string"&&fish.trim(c.theme).length&&
i.addClass(c.theme);if(typeof c.itemClass==="string"&&fish.trim(c.itemClass).length)l=c.itemClass;if(typeof c.highlightClass==="string"&&fish.trim(c.highlightClass).length)$=c.highlightClass;if(typeof c.emptyClass==="string"&&fish.trim(c.emptyClass).length)T=c.emptyClass;if(typeof c.ajaxFn==="function")U=c.ajaxFn;H=c.width?c.width:H;A=c.processPrintDataFn?c.processPrintDataFn:A;D=c.preSortFn?c.preSortFn:D;F=c.max?c.max:F;E=c.sortFn?c.sortFn:E;N=c.keepListOnNoResult?c.keepListOnNoResult:N;x=c.requestUrl?
c.requestUrl:x;K=c.requestType?c.requestType:K;B=c.itemPrintFn?c.itemPrintFn:B;O=c.itemEnableFn?c.itemEnableFn:O;s=c.itemValueFn?c.itemValueFn:s;w=c.localData?c.localData:w;P=c.itemHighlightFn?c.itemHighlightFn:P;H&&fish.all(j).css("width:"+H+"px");aa(i,h,G);i.css("display:none");i.effect({elem:h,interShow:false});var y;h.on("keyup",function(a){var b=fish.getTarget(a),d;a=fish.getEvent(a);d=a.which?a.which:a.keyCode;a=j;if(fish.trim(b.value)!==b.value)b.value=fish.trim(b.value);if(b.value===""||b.value===
c.placeholder)e.hide();else{e.show();if(d===13){d=fish.all("."+l,a);c.submit&&c.submit(e);p[a.index]&&h.val(s.call(d[a.index],p[a.index],a.index));e.hide()}else if(d===40||d===38){b=h;var f=fish.all("."+l,a),g=f.length-1;if(f.length){f.removeClass(q);switch(d){case 40:do a.index++;while(f[a.index]&&!fish.one(f[a.index]).hasClass(t));if(a.index>g){a.index=-1;b.val(b.origin)}else{fish.one(f[a.index]).addClass(q);b.val(s.call(f[a.index],p[a.index],a.index))}break;case 38:do a.index--;while(f[a.index]&&
!fish.one(f[a.index]).hasClass(t));if(a.index===-1)b.val(b.origin);else{if(a.index<-1)a.index=g;fish.one(f[a.index]).addClass(q);b.val(s.call(f[a.index],p[a.index],a.index))}}}}else(a=x&&x.call(e,e.val()))?ba(a):Z(e.val())}});i.on("mouseover",function(a){var b=fish.getTarget(a),d,f,g=j;for(f=fish.all("."+l,g);b!==null;){d=fish.one(b);if(d.hasClass(l)){f.removeClass(q);f.each(function(k,m){if(k===b&&fish.one(b).hasClass(t)){d.addClass(q);g.index=m;h.val(s.call(f[g.index],p[g.index],g.index));return false}});
break}b=b.parentNode}});i.on("click",function(a){var b=fish.getTarget(a),d,f,g=j;for(f=fish.all("."+l,g);b!==null;){d=fish.one(b);if(d.hasClass(l)){f.each(function(k,m){if(k===b&&fish.one(b).hasClass(t)){d.addClass(q);g.index=m;h.val(s.call(f[g.index],p[g.index],g.index));return false}});e.hide();break}b=b.parentNode}});fish.one(".autofill_close",i).on("click",function(){e.hide()});h.on("mousedown",function(){v=true});h.on("mouseup",function(){v=false});i.on("mousedown",function(){v=true});i.on("mouseup",
function(){v=false});h.on("focus",function(a){a=fish.getTarget(a);if(fish.trim(a.value)===c.placeholder){a.value="";fish.one(a).removeClass(T)}});h.on("blur",function(a){a=fish.getTarget(a);if(!fish.trim(a.value)||fish.trim(a.value)===c.placeholder){a.value=c.placeholder;fish.one(a).addClass(T)}setTimeout(function(){if(!v){e.hide();v=false}},0)});fish.one(window).on("resize",function(){e.resetPosition()});e.macth=function(){Z(e.val())};e.hide=function(){i.css("display:none")};e.show=function(){if(i.getCss("display")===
"none"){i.css("display:block");e.resetPosition();I()}};e.setTitle=function(a){S.html(a)};e.val=function(a){return h.val(a)};e.resetPosition=function(){aa(i,h,G)};e.requestUrl=function(a){if(typeof a==="function")x=a};e.localData=w;return e}})})();
