(function(c){c.extend({mNotice:function(d){function A(a){var b=true;a=c.all(a);if(a.length){a.each(function(e){if(!(c.one(e).hasClass("none")||e.style.display==="none"))return b=false});return b}else return 1}function B(a){if(a=C.apply(h,[a,D])){f.html("");f.html(a);j=true}else j=false}function E(a,b){var e;L||M(h);if(e=C.apply(h,[a,D])){f=N(e,b);j=true;F==="mTab"&&O(F,h,b);P(h,f);Q&&R(f,h);if(S){T(f);U(f)}V(h,f);W(f,h);if(c.one(".mNotice-close",f).length)f.on("click",function(g){g=c.getTarget(g);
c.one(g).hasClass("mNotice-close")&&f.addClass("none")})}else j=false}function m(){if(!p){var a=document.createElement("iframe");a.id="mNotice-backdrop";fish.one(f).html("top",a);c.one(a).css("position:absolute;border:none;filter:alpha(opacity=0);opacity:0;z-index:-1");p=a}a=fish.one(f).width();var b=fish.one(f).height();fish.all(p).css("width:"+a+"px;height:"+b+"px")}function N(a,b){f=document.createElement("div");var e=c.one(f);n&&e.attr("data-box-type",n);f.id="mNotice-"+b;f.className=G?"mNotice-wrap none "+
G:"mNotice-wrap none";e.css("position: absolute; z-index: 1000000;");document.body.insertBefore(f,document.body.firstChild);f.innerHTML=a;m();return e}function O(a,b,e){a==="mTab"&&c.one("#mNotice-"+e).mTab({tab_tray:".mNotice-mTab-tab-tray",append:"current",content:".mNotice-mTab-content",fn:function(){q();m()}})}function P(a,b){a.on(X,function(){c.all("body .mNotice-wrap").addClass("none");if(j&&A(H)){b.removeClass("none");l(b,a,o);m()}})}function M(a){a.on("click",function(){a[0].select()})}function R(a,
b){a.on(Y,function(e){e=c.getTarget(e);if(c.one(e).hasClass("mNotice-normal")){b.val(e.innerHTML);b.attr("cid",e.getAttribute("cid"));b.attr("ctype",e.getAttribute("ctype"));b.addClass("color-normal");a.addClass("none");n&&setTimeout(function(){c.dom("#"+n).blur()},20);I&&I.apply(c.one(e),[b])}})}function T(a){a.on("mouseover",function(b){b=c.getTarget(b);if(c.one(b).hasClass("mNotice-normal")){c.all(".mNotice-normal",a).removeClass("mNotice-hover");c.one(b).addClass("mNotice-hover")}})}function U(a){a.on("mouseout",
function(){c.all(".mNotice-normal",a).removeClass("mNotice-hover")})}function W(a,b){c.one(document).on("mousedown",function(e){for(var g=c.getTarget(e);g!==null;){if(g.nodeType===1&&(g===b[0]||g.className.indexOf("mNotice-wrap")>-1)){fish.one(g).attr("data-box-type")&&setTimeout(function(){fish.dom("#"+fish.one(g).attr("data-box-type")).focus()},0);return}g=g.parentNode}a.addClass("none")})}function V(a,b){a.on("keydown",function(e){e=c.getEvent(e);key=e.keyCode||e.which;typeof key==="number"&&key!==
17&&key!==18&&b.addClass("none")})}function l(a,b,e){var g=e;if(a&&a[0].nodeType===1&&b&&b[0].nodeType===1){a.css("left:-1000px;");e=c.one(window).width();c.one(window).height();var Z=b.width(),$=b.height(),J=a.width();a.height();b=b.offset();c.one(document).scrollTop();var r=c.one(document).scrollLeft();if(g&&!s(g)){g.x=typeof g.x==="number"?g.x:0;g.y=typeof g.y==="number"?g.y:0}else g={x:0,y:0};b.left-r>e-(b.left-r)&&e-(b.left-r)<J?a.css("left:"+(b.left+Z-J-g.x)+"px"):a.css("left:"+(b.left+g.x)+
"px");a.css("top:"+(b.top+$+g.y)+"px")}else l(f,h,e)}function q(){if(!(!f||f.hasClass("none"))){t&&clearTimeout(t);t=setTimeout(function(){l(f,h,o);m()},100)}}function s(a){for(var b in a)return false;return true}function K(a){if(!window.iError)window.iError=[];window.iError.push({date:(new Date).toString(),info:a})}var u=fish.guid();if(!d)throw Error("\u4f20\u9012\u8bbe\u7f6e\u53c2\u6570\uff01");var h=d.beside,n=d.dataBoxType,L=d.isSelect,X=d.documentCaptureEvent?d.documentCaptureEvent:"focus",Y=
d.inputCaptureEvent?d.inputCaptureEvent:"click";if(this.length)h=c.one(this[0]);else{if(!h||typeof h!=="string"&&h.nodeType!==1&&!h.length)throw Error("\u6307\u5b9a\u9700\u8981\u5f39\u6846\u7684\u8282\u70b9\u9009\u62e9\u5668\u6216\u8282\u70b9\uff01");h=c.one(h);if(!h.length)throw Error("\u6307\u5b9a\u9700\u8981\u5f39\u6846\u7684\u8282\u70b9\uff01");}if(!{INPUT:"INPUT",TEXTAREA:"TEXTAREA"}[h[0].nodeName])throw Error("\u6307\u5b9a\u7684\u8f93\u5165\u57df\u65e0\u6548\uff01");var o={x:0,y:0},v=d.offset&&
d.offset.x,w=d.offset&&d.offset.y,i=d.request,k=d.localData,D=typeof d.template==="string"?d.template:undefined,F=d.mode==="mTab"?"mTab":"",p,C=d.display,Q=d.isClick===undefined?false:!!d.isClick,S=d.isHover===undefined?false:!!d.isHover,I=typeof d.clickCallback==="function"?d.clickCallback:false,G=typeof d.theme==="string"?d.theme:"",x=typeof d.urlInTime==="function"?d.urlInTime:false,H=typeof d.rejects==="string"?d.rejects:false,y="",f,j,t,z={};if(d.offset&&(parseInt(v)||parseInt(w))){v&&(o.x=v);
w&&(o.y=w)}if(!d.display&&typeof d.display!=="function")throw Error("\u6307\u5b9a\u6570\u636e\u6e32\u67d3\u51fd\u6570\uff01");if(!i&&!k||i&&k)throw Error("\u6307\u5b9a\u552f\u4e00\u6570\u636e\u6e90\uff01");else if(i&&x){y=i.url;i.url=x(y);i.fn=function(a){if(a&&(a.length||!s(a)))c.ready(function(){z[i.url.substring(i.url.indexOf("?")+1)]=a;c.all("#mNotice-"+u).length?B(a):E(a,u)})};i.onTimeout=function(){K("\u670d\u52a1\u5668\u7aef\u54cd\u5e94\u8d85\u65f6\uff01")};i.err=function(){K("\u670d\u52a1\u5668\u7aef\u53d1\u751f\u9519\u8bef\uff01")};
c.ajax(i)}else c.ready(function(){if(k&&(k.length||!s(k)))E(k,u)});c.ready(function(){c.one(window).on("resize",q);c.one(window).on("scroll",q)});return{show:function(){setTimeout(function(){j&&A(H)&&f.removeClass("none")&&l()},0)},hide:function(){f&&f.length&&f.addClass("none")},position:l,update:function(){var a;i.url=x(y);a=i.url.substring(i.url.indexOf("?")+1);z[a]?B(z[a]):c.ajax(i)}}}})})(fish);
