(function(){function K(a){a.single_cal_width=(a.eachWidth+3)*7;a.cal_height=(a.eachHeight+3)*6+4;a.tol_cal_width=(a.single_cal_width+10)*a.monthNum-10}function x(a,b){var c,d;K(a);var h=a.inputElem,g,i;if(h){b&&a.beforeOpen&&a.beforeOpen.call(a);if((c=h.getAttribute("data-mcalId"))==null){h.setAttribute("data-mcalId",++F);a.mCalId=F;c=document.createElement("div");d=document.createElement("iframe");var m=document.createElement("div");g=document.createElement("div");var j="",r="",p="<div class = 'top'>",
n="";a.calElem=c;c.id="mCalendar"+a.mCalId;c.onselectstart=function(){return false};document.body.insertBefore(c,document.body.firstChild);d.className="if";d.src="http://img1.40017.cn/cn/new_ui/public/images/png_cover.png";c.appendChild(d);m.className="date";c.appendChild(m);m.appendChild(g);g.className="top";g=0;for(i=a.monthNum;g<i;g++){if(g==0&&i==1){j=y(a,"one");r=z(a,"first")}else if(g==0){j=y(a,"first");r=z(a,"first")}else if(g==i-1){j=y(a,"last");r=z(a,"last")}else{j=y(a,"mcal"+g,g);r=z(a,
"mcal"+g)}p+=j;n+=r}p+="</div>";m.innerHTML=p+n;a.top_height=27;a.th_height=fish.one("th",a.calElem).height();a.cal_head_height=a.top_height+a.th_height;fish.one(c).css("width:"+(a.tol_cal_width+4)+"px;height:"+(a.cal_height+a.cal_head_height+4)+"px;");d.style.cssText="width:"+(a.tol_cal_width+4)+"px;height:"+(a.cal_height+a.cal_head_height+4)+"px;";fish.one(m).css("width:"+a.tol_cal_width+"px;");c.className="mCalendar";fish.all(a.calElem).css("display:none;")}else{if(!a.calElem&&(d=fish.all("#mCalendar"+
c)).length)a.calElem=d[0];fish.all(a.calElem).css("display:block;");a.top_height=27;a.th_height=fish.one("th",a.calElem).height();a.cal_head_height=a.top_height+a.th_height;fish.one(a.calElem).css("display:none;")}fish.dom("#mCalendar"+a.mCalId+" .date_lastSpan").onclick=function(){a._DFirstDrawTime=fish.parseDate(a._DFirstDrawTime,{months:-a.monthNum});B(a)};fish.dom("#mCalendar"+a.mCalId+" .date_nextSpan").onclick=function(){a._DFirstDrawTime=fish.parseDate(a._DFirstDrawTime,{months:a.monthNum});
B(a)};if(!h.bindCal){c=h.tagName==="INPUT"?fish.all(h):fish.all();if(a.elem){c[c.length]=a.elem;c.length++;fish.all(c).on("click",function(){x(a,true)})}c[c.length]=fish.dom(".date",a.calElem);c.length++;fish.all(c).on("focus",function(){x(a,true)});fish.all(c).on("keydown",function(f){var t;if(f&&f.keyCode)t=f.keyCode;else if(f&&f.which)t=f.which;t===9&&A(a)});fish.all(c).on("change",function(){var f=fish.trim(this.value);f=fish.parseTime(f);this.value=a.showPast?f:fish.parseDate(f).getTime()<fish.parseDate(a.startTime).getTime()?
a.startTime:f});switch(a.showType){case "pop":break;case "static":break;default:fish.all(a.calElem).effect({elem:c,type:"click",interShow:false,outerHide:false,outerFn:function(){A(a)}})}h.bindCal=true}if(a.calElem){a.calElem.className="mCalendar"+(a.css?" "+a.css:"");a.now=h.value?h.value:fish.parseTime(a.now);a._DFirstDrawTime=fish.parseDate(h.value);a._DFirstDrawTime.setDate("1");c=parseInt(a.now.split("-")[1],10);a._addNum=c&&!(c%2)?-1:0;if(b){B(a);switch(a.showType){case "pop":fish.all(a.calElem).css("position: static");
fish.require("mPop",function(){if(fish.all(a.calElem).getCss("display")!=="block"){fish.all(a.calElem).css("display:block;");fish.mPop({content:a.calElem,afterClose:function(){fish.all(a.calElem).css("display:none;")}})}});break;case "static":fish.all(a.calElem).css("position: relative;display:block");fish.one(a.inputElem).css("display:block").html("top",a.calElem);break;default:c=fish.one(h).offset();h=fish.one(h).height();d=fish.one(window).width();d=d-c.left>=a.tol_cal_width+20?c.left:c.left-20-
(a.tol_cal_width-(d-c.left));fish.all(a.calElem).css("top:"+(c.top+h)+"px; left:"+d+"px;");fish.all(a.calElem).css("display:block;")}}}}}function y(a,b,c){var d="<div class = 'floatL' style = 'width:"+a.single_cal_width+"px;'>";if(b=="one")return d+"<h4 class='lastText mCalTitleFir'  style = 'width:"+a.single_cal_width+"px;'><span class='lastMonthBg date_lastSpan'><span class='lastMonth'></span></span><span class='nextMonthBg date_nextSpan'><span class='nextMonth' ></span></span><span class=date_title>....\u5e74..\u6708</span></h4></div>";
else if(b=="first")return d+"<h4 class='lastText  mCalTitleFir'  style = 'width:"+a.single_cal_width+"px;'><span class='lastMonthBg date_lastSpan'><span class='lastMonth'></span></span><span class=date_title>....\u5e74..\u6708</span></h4></div>";else if(b=="last"){d="<div class = 'floatL' style = 'width:"+a.single_cal_width+"px;margin-left:10px'>";return d+"<h4 class='nextText  mCalTitleLast' style = 'width:"+a.single_cal_width+"px;'><span class='nextMonthBg date_nextSpan' ><span class='nextMonth' ></span></span><span class=date_title>....\u5e74..\u6708</span></h4></div>"}else{d=
"<div class = 'floatL' style = 'width:"+a.single_cal_width+"px;margin-left:10px'>";return d+"<h4 class='normalText mCalTitleMid"+c+"' style = 'width:"+a.single_cal_width+"px;'><span class='nomalMonthBg'></span><span class=date_title>....\u5e74..\u6708</span></h4></div>"}}function z(a,b){var c="";if(b=="first"){c="<div class = 'contentTime1 contentTime clearfix'>";c+="<table cellspacing='0' cellpadding='0' class='tbl_lastMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg' >1</i>"}else if(b==
"last"){c="<div class = 'contentTime2 contentTime clearfix'>";c+="<table cellspacing='0' cellpadding='0' class='tbl_nextMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg'>12</i>"}else{c="<div class = 'contentTimeMiddle contentTime clearfix'>";c+="<table cellspacing='0' cellpadding='0' class="+b+" border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg' >1</i>"}c+=
"</div>";return c}function u(a,b,c,d,h,g){var i=fish.dom(a),m=i.parentNode,j=fish.dom(h+" .date_title"),r=fish.all("td",i),p=i.parentNode.getElementsByTagName("i"),n=d.getFullYear(),f=d.getMonth()+1,t=d.getDay(),v=new Date,C=v.getFullYear(),D=v.getMonth()+1;v=v.getDate();var L=0,o=b.ajaxUrl,k;if(p.length>0){if(!g){p[0].innerHTML=parseInt(f,10);fish.all(p[0]).removeClass("loadingbg");r.removeClass("none")}fish.one(p[0]).css("height:"+(b.cal_height+b.cal_head_height)+"px;line-height:"+(b.cal_height+
b.cal_head_height)+"px;width:"+b.single_cal_width+"px");fish.one(p[0]).removeClass("none")}j.innerHTML=n+"\u5e74"+f+"\u6708";fish.one(m).css("height:"+(b.cal_height+b.th_height)+"px;width:"+b.single_cal_width+"px");fish.all("th",i).css("width:"+(b.eachWidth+3)+"px");if(g){p[0].innerHTML=parseInt(f,10);fish.all(p[0]).removeClass("loadingbg");r.removeClass("none")}else if(b.processDataFn&&b.dateTempleteFn&&o&&typeof b.processDataFn=="function"){g=typeof o==="function"?o():o;g=g.replace("{year}",n);
g=g.replace("{month}",f);p[0].innerHTML="";fish.all(p[0]).addClass("loadingbg");r.addClass("none");if(b.ajaxObj[c]){b.ajaxObj[c].abort();b.ajaxObj[c]=null}b.ajaxObj[c]=fish.ajax({url:g,type:"json",fn:function(w){b.ajaxObj[c]=null;if(w)(w=b.processDataFn(w))?u(a,b,c,d,h,w):u(a,b,c,d,h,[])},err:function(){b.ajaxObj[c]=null;u(a,b,c,d,h,[])}});return}b.isDebug&&d.getDate()!=1&&window.console&&console.error("\u4f20\u5165\u7684DDrawDate\u7684\u5fc5\u987b\u4e3a\u5f53\u6708\u7684\u7b2c\u4e00\u5929\uff01\uff01\uff01");
r=i.getAttribute("inited")=="true";var G;p=M(d);if(t!=7)p+=t;var H;m=true;if(r){H=fish.all("tr",i);tds=fish.all("td",i);items=fish.all(".itemWrap",i)}for(j=1;j<=42;j++){o=j-t;if(j%7==1)G=r?H[parseInt(j%7,10)]:i.insertRow(i.rows.length);var l;if(r){k=tds[j-1];e=items[j-1];l=fish.dom(".dateWrap",e);l.className="dateWrap";e.className="itemWrap"}else{k=G.insertCell(j%7-1);k.innerHTML="";var e=document.createElement("div");l=document.createElement("span");var q=document.createElement("div");l.className=
"dateWrap";e.className="itemWrap";q.className="useWrap";e.style.cssText="height:"+b.eachHeight+"px;width:"+b.eachWidth+"px;float:left;display:inline;overflow:hidden;position:relative;";k.appendChild(e);e.appendChild(l);e.appendChild(q)}if(t!=7&&j<=t||j>p){l.innerHTML="";fish.one(".useWrap",e).html("");k.className="td02";e.className="spanOut itemWrap";e.onmouseover=e.onmouseout=e.onclick=null}else{k.className="td01";k=N(n,f,o);if(k==-1){l.innerHTML=o;e.className+=" spanOut";e.setAttribute("s","false");
e.setAttribute("d",o)}else{l.innerHTML="";l.className=l.className+" "+k.className;e.className+=" spanOut";e.setAttribute("s","true");e.setAttribute("r",e.className);e.setAttribute("d",k.day)}k=fish.one(".useWrap",e);if(b.dateTempleteFn&&typeof b.dateTempleteFn=="function"&&g){m=b.dateTempleteFn(n,f,o,g[L++]);m!==false?k.html(m):k.html("")}f<10?e.setAttribute("m",n+"-0"+f):e.setAttribute("m",n+"-"+f);if(m===false&&k&&k.length){fish.one(k[0].parentNode)[0].className="itemWrap spanOver";e.onmouseover=
e.onmouseout=null}else{e.onmouseover=function(){if(this.getAttribute("s")=="true")this.className=this.getAttribute("r")+" hover";else fish.one(this).addClass("spanHover")};e.onmouseout=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r"):"itemWrap spanOut"}}q=false;if(C>n)q=true;else if(C==n)if(D>f)q=true;else if(D==f)if(v>o)q=true;if(b.endTime){var s=b.endTime.split("-");if(s.length>0)if(parseInt(s[0])<n)q=true;else if(parseInt(s[0])==n)if(parseInt(s[1],10)<f)q=true;else if(parseInt(s[1],
10)==f)if(parseInt(s[2],10)<o)q=true}if(b.startTime){s=b.startTime.split("-");if(s.length>0)if(parseInt(s[0],10)>n)q=true;else if(parseInt(s[0])==n)if(parseInt(s[1],10)>f)q=true;else if(parseInt(s[1],10)==f)if(parseInt(s[2],10)>parseInt(o,10))q=true}if(q&&!b.showPast){e.className="itemWrap spanOver";l.className="dateWrap";if(l.innerHTML=="")l.innerHTML=e.getAttribute("d");e.onmouseover=e.onmouseout=e.onclick=null}else e.onclick=m!==false&&k&&k.length?function(){var w=this,I=this.getAttribute("m"),
E=this.getAttribute("d")?this.getAttribute("d"):this.innerHTML;b.now=I+"-"+E;if(parseInt(E,10)<=9)b.now=I+"-0"+E;if(b.inputElem.tagName==="INPUT"){b.inputElem.value=b.now;b.inputElem&&b.showDay&&O(b.inputElem,b.now,b)}A(b,function(){setTimeout(function(){b.fn&&b.fn.call(b,b.now,w)})})}:null;if(C==n&&D==f&&v==o){l.innerHTML="";l.className="spanDay dateWrap";e.setAttribute("d",o);e.setAttribute("s","true");e.setAttribute("r",e.className)}if(fish.parseTime(n+"-"+f+"-"+o)==fish.parseTime(new Date,{days:1})){l.innerHTML=
"";l.className="spanTomo dateWrap";e.setAttribute("s","true");e.setAttribute("d",o);e.setAttribute("r",e.className)}if(b.now!=null){l=b.now.split("-")[0];k=b.now.split("-")[1];q=b.now.split("-")[2];if(P(new Date(l,k,q),new Date(n,f,o),b)){e.className=e.getAttribute("s")=="true"?e.getAttribute("r")+" clickDate":"clickDate itemWrap";e.onmouseout=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r")+" clickDate":"clickDate itemWrap"}}}e.className+=" dateWrap"}}i.setAttribute("inited",
"true")}function A(a,b){switch(a.showType){case "pop":fish.require("mPop",function(){fish.mPop.close()});break;case "static":break;default:a.calElem.style.display="none"}b&&b()}function J(a){a=a||{};var b={css:"",open:false,startTime:fish.parseTime(new Date),endTime:"",inputElem:this[0],showPast:false,fn:null,calElem:null,now:fish.parseTime(new Date),beforeOpen:function(){},fontSize:12,_DFirstDrawTime:null,eachHeight:30,eachWidth:30,eachCalMargin:10,monthNum:2,showDay:false,isAjax:false,ajaxFn:false};
b.ajaxObj=[];for(var c=a.monthNum;c--;)b.ajaxObj[c]=null;if(b.inputElem&&b.inputElem.getAttribute("data-mcalid")!=null)b.mCalId=b.inputElem.getAttribute("data-mcalid");fish.lang.extend(b,a);x(b,b.open);return{setAjaxUrl:function(d){b.ajaxUrl=d}}}function P(a,b,c){var d=fish.parseDate(c.startTime);if(a-b===0)if(c.showPast)return true;else if(a-d>=0)return true;return false}function N(a,b,c){var d={specialDate:[{date:"2011-01-01",name:"\u5143\u65e6",className:"yuandan"},{date:"2011-12-25",name:"\u5723\u8bde\u8282",
className:"\u5723\u8bde"},{date:"2012-01-01",name:"\u5143\u65e6",className:"yuandan"},{date:"2012-02-22",name:"\u9664\u5915",className:"chuxi"},{date:"2012-04-04",name:"\u6e05\u660e",className:"qingming"},{date:"2012-05-01",name:"\u52b3\u52a8\u8282",className:"wuyi"},{date:"2012-06-01",name:"\u513f\u7ae5\u8282",className:"liuyi"},{date:"2012-06-23",name:"\u7aef\u5348",className:"duanwu"},{date:"2012-08-23",name:"qixi",className:"qixi"},{date:"2012-09-30",name:"\u4e2d\u79cb",className:"zhongqiu"},
{date:"2012-10-01",name:"\u56fd\u5e86",className:"guoqing"},{date:"2012-12-25",name:"\u5723\u8bde",className:"shendan"},{date:"2013-01-01",name:"\u5143\u65e6",className:"yuandan"}]};a:{a=new Date(a,b-1,c);if(d){d=d.specialDate;var h,g;c=-1;c=0;for(h=d.length;c<h;c++){b=d[c];g=b.date;var i=g=new Date(g.replace(/-/g,"/")),m=a;i.getFullYear();i.getMonth();i.getDate();m.getFullYear();m.getMonth();m.getDate();var j=false;if(i.getTime()==m.getTime())j=true;if(j){c={};c.name=b.name;c.className=b.className;
c.day=g.getDate()+"";a=c;break a}}}a=-1}return a}function B(a){var b=a._DFirstDrawTime,c,d;c=u.markCount=0;for(d=a.monthNum;c<d;c++){if(c==0)u("#mCalendar"+a.mCalId+" .tbl_lastMonth",a,c,b,"#mCalendar"+a.mCalId+" .mCalTitleFir");else c==d-1?u("#mCalendar"+a.mCalId+" .tbl_nextMonth",a,c,b,"#mCalendar"+a.mCalId+" .mCalTitleLast"):u("#mCalendar"+a.mCalId+" .mcal"+c,a,c,b,"#mCalendar"+a.mCalId+" .mCalTitleMid"+c);b=fish.parseDate(b,{months:1});u.markCount++}}function M(a){a=new Date(a);a.setMonth(a.getMonth()+
1);a.setDate(0);return a.getDate()}function O(a,b,c){b=fish.parseDate(b).getDay();var d=fish.one(".mCalendar"+c.mCalId);a=fish.one(a);if(d.length==0){d=fish.one(document.createElement("div"));d.addClass("dayWrap");d.addClass("mCalendar"+c.mCalId);d.css("height:"+a.height()+"px;line-height:"+a.height()+"px;left:"+(a.offset().left+a.width()-52)+"px;top:"+a.offset().top+"px;font-size:"+Q(a)+";");document.body.appendChild(d[0]);d.on("click",function(){x(c,true)})}switch(b){case 1:b="\u4e00";break;case 2:b=
"\u4e8c";break;case 3:b="\u4e09";break;case 4:b="\u56db";break;case 5:b="\u4e94";break;case 6:b="\u516d";break;case 0:b="\u65e5"}d.html("\u661f\u671f"+b)}function Q(a){try{return fish.one(a).getCss("font-size")}catch(b){return 12}}var F=0;J.close=A;fish.extend({mCal:J,preventInput:function(a){fish.all(a?a:this).each(function(b){if(!b.getAttribute("_preventInput_")){b.style.imeMode="disabled";b.onkeydown=function(c){fish.preventDefault(c)};b.oncontextmenu=function(){return false};b.onselectstart=function(){return false};
b.setAttribute("_preventInput_","true")}})},recoverInput:function(a){fish.all(a?a:this).each(function(b){if(b.getAttribute("_preventInput_")){b.style.imeMode="";b.onkeydown=b.oncontextmenu=b.onselectstart=null;b.setAttribute("_preventInput_","")}})}})})();
