(function(){fish.extend({autoComplete:function(c){function I(){if(!J){var a=document.createElement("iframe");a.id="mNotice-backdrop";fish.one(i).html("top",a);fish.one(a).css("position:absolute;border:none;filter:alpha(opacity=0);opacity:0;z-index:-1");J=a}a=fish.one(i).width();var d=fish.one(i).height();fish.all(J).css("width:"+a+"px;height:"+d+"px")}function ba(a){y&&clearTimeout(y);y=setTimeout(function(){if(h.ajaxObj)try{h.ajaxObj.abort()}catch(d){}h.ajaxObj=fish.ajax({url:a,type:K,fn:function(b){U(b);
b=V(b);h.origin=e.val();if(b&&b.length){e.setTitle(L);M(b)}else{N&&M();b="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(e.val());e.setTitle(b)}I()}});y=null},200)}function M(a,d){a&&A&&A.call(e,a);p=a;var b;W(j);if(a&&a.length){for(n=0;n<a.length;n++){row=j.insertRow(-1);cell=row.insertCell(-1);b=O.call(row,a[n],n);row.className=l;if(b)row.className+=" "+t;b=B.call(row,a[n],n);if(b===false)j.deleteRow(-1);else cell.innerHTML=P.call(row,a[n],n)?z(b,d):b}if(j.index!==-1){for(b=fish.all("."+l,
j);b[j.index]&&!fish.one(b[j.index]).hasClass(t);)j.index++;if(b[j.index])fish.one(b[j.index]).addClass(q);else j.index=-1}}}function X(a){var d=[],b,f,g,k,m,u,o,r,C,Y;r=w.length;for(o=0;o<r;o++){b=w[o];f=b.match;Y=f.length;k=-1;for(C=0;C<Y;C++){g=f[C];if(Q)g=g.toLowerCase();if((m=g.indexOf(a))>-1&&(k===-1||m<k)){k=m;u=g}}if(k>-1){D&&D(b,u,k);d[d.length]=b}}if(d.length)d.matchLength=a.length;else{a=a.substr(0,a.length-1);if(a!=="")d=X(a);d.matchFalid=true}return d}function Z(a){var d;if(Q)a=a.toLowerCase();
d=X(a);h.origin=a;if(d.length){E&&d.sort(E);F&&d.splice(F,d.length);if(d.matchFalid){var b="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(a);e.setTitle(b)}else e.setTitle(L);M(d,a.substr(0,d.matchLength))}else{a="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(a);e.setTitle(a);W(j)}I()}function z(a,d){if(ca){var b=d?d:e.val(),f=RegExp(b,"g"+(Q?"i":""));return a.replace(/(>|^)([^>^<]+)(<|$)/g,function(g){return g.replace(f,function(k){return'<span class="'+$+'">'+k+"</span>"})})}else return a}
function aa(a,d,b){if(a&&a[0].nodeType===1&&d&&d[0].nodeType===1){var f=fish.one(window).width();fish.one(window).height();var g=d.width(),k=d.height(),m=a.width();a.height();d=d.offset();fish.one(document).scrollTop();var u=fish.one(document).scrollLeft(),o;if(o=b){var r;a:{for(r in b){r=false;break a}r=true}o=!r}if(o){b.x=typeof b.x==="number"?b.x:0;b.y=typeof b.y==="number"?b.y:0}else b={x:0,y:0};d.left-u>f-(d.left-u)&&f-(d.left-u)<m?a.css("left:"+(d.left+g-m-b.x)+"px"):a.css("left:"+(d.left+b.x)+
"px");a.css("top:"+(d.top+k+b.y)+"px")}else throw Error("\u9700\u8981\u6307\u5b9a\u8f93\u5165\u57df\u548c/\u6216\u53ca\u5176\u5f39\u6846\uff01");}function W(a){a.index=da;for(var d=fish.all("."+l,a).length;d-- >0;)a.deleteRow(-1)}var h,R=fish.guid(),i,S,w=[],p={},G={x:0,y:0},L="\u8f93\u5165\u4e2d\u6587/\u62fc\u97f3/\u2191\u2193\u952e\u9009\u62e9",e={},D=null,E=null,H,ca=true,F=10,da=0,N=false,x="",K="get",Q=true,A,V=function(){},B=function(){},s=function(){},O=function(){return true},U=function(){},
P=function(){return true},v=false,j,J,l="autofill_item",t="enableListRow",q="autofill_hover",$="autofill_hili",T="autofill_empty";h=this;if(!h[0])throw Error("autoComplete init faild, fish obj was null when exec fish.all('...').autoComplete()");fish.one("body").html("top",'<div id="autoComplete-'+R+'" class="autofill_wrap"><table class="autofill_tray" cellpadding="0" cellspacing="0"><tr class="autofill_title"><th class="autofill_hd"><span class="autofill_hd_inner"></span></th></tr></table><span class="autofill_close"></span></div>');
i=fish.one("#autoComplete-"+R);S=fish.one(".autofill_hd_inner",i[0]);j=fish.dom(".autofill_tray",i[0]);G.x=c.offsetX!==undefined?c.offsetX:0;G.y=c.offsetY!==undefined?c.offsetY:0;if(typeof c.processAjaxDataFn==="function")V=c.processAjaxDataFn;if(typeof c.itemPrintFn==="function")B=c.itemPrintFn;if(typeof c.template==="string"&&fish.trim(c.template).length)R=c.template;if(typeof c.title==="string"&&fish.trim(c.title).length){L=c.title;S.html(c.title)}typeof c.theme==="string"&&fish.trim(c.theme).length&&
i.addClass(c.theme);if(typeof c.itemClass==="string"&&fish.trim(c.itemClass).length)l=c.itemClass;if(typeof c.highlightClass==="string"&&fish.trim(c.highlightClass).length)$=c.highlightClass;if(typeof c.emptyClass==="string"&&fish.trim(c.emptyClass).length)T=c.emptyClass;if(typeof c.ajaxFn==="function")U=c.ajaxFn;H=c.width?c.width:H;A=c.processPrintDataFn?c.processPrintDataFn:A;D=c.preSortFn?c.preSortFn:D;F=c.max?c.max:F;E=c.sortFn?c.sortFn:E;N=c.keepListOnNoResult?c.keepListOnNoResult:N;x=c.requestUrl?
c.requestUrl:x;K=c.requestType?c.requestType:K;B=c.itemPrintFn?c.itemPrintFn:B;O=c.itemEnableFn?c.itemEnableFn:O;s=c.itemValueFn?c.itemValueFn:s;w=c.localData?c.localData:w;P=c.itemHighlightFn?c.itemHighlightFn:P;H&&fish.all(j).css("width:"+H+"px");aa(i,h,G);i.css("display:none");i.effect({elem:h,interShow:false});var y;h.on("keyup",function(a){fish.getTarget(a);var d;a=fish.getEvent(a);d=a.which?a.which:a.keyCode;a=j;var b;b=e.val();if(b===""||b===c.placeholder)e.hide();else{e.show();if(d===13){d=
fish.all("."+l,a);c.submit&&c.submit(e);p[a.index]&&h.val(s.call(d[a.index],p[a.index],a.index));e.hide()}else if(d===40||d===38){b=h;var f=fish.all("."+l,a),g=f.length-1;if(f.length){f.removeClass(q);switch(d){case 40:do a.index++;while(f[a.index]&&!fish.one(f[a.index]).hasClass(t));if(a.index>g){a.index=-1;b.val(b.origin)}else{fish.one(f[a.index]).addClass(q);b.val(s.call(f[a.index],p[a.index],a.index))}break;case 38:do a.index--;while(f[a.index]&&!fish.one(f[a.index]).hasClass(t));if(a.index===
-1)b.val(b.origin);else{if(a.index<-1)a.index=g;fish.one(f[a.index]).addClass(q);b.val(s.call(f[a.index],p[a.index],a.index))}}}}else(a=x&&x.call(e,b))?ba(a):Z(b)}});i.on("mouseover",function(a){var d=fish.getTarget(a),b,f,g=j;for(f=fish.all("."+l,g);d!==null;){b=fish.one(d);if(b.hasClass(l)){f.removeClass(q);f.each(function(k,m){if(k===d&&fish.one(d).hasClass(t)){b.addClass(q);g.index=m;h.val(s.call(f[g.index],p[g.index],g.index));return false}});break}d=d.parentNode}});i.on("click",function(a){var d=
fish.getTarget(a),b,f,g=j;for(f=fish.all("."+l,g);d!==null;){b=fish.one(d);if(b.hasClass(l)){f.each(function(k,m){if(k===d&&fish.one(d).hasClass(t)){b.addClass(q);g.index=m;h.val(s.call(f[g.index],p[g.index],g.index));return false}});e.hide();break}d=d.parentNode}});fish.one(".autofill_close",i).on("click",function(){e.hide()});h.on("mousedown",function(){v=true});h.on("mouseup",function(){v=false});i.on("mousedown",function(){v=true});i.on("mouseup",function(){v=false});h.on("focus",function(a){a=
fish.getTarget(a);if(fish.trim(a.value)===c.placeholder){a.value="";fish.one(a).removeClass(T)}});h.on("blur",function(a){a=fish.getTarget(a);if(!fish.trim(a.value)||fish.trim(a.value)===c.placeholder){a.value=c.placeholder;fish.one(a).addClass(T)}setTimeout(function(){if(!v){e.hide();v=false}},0)});fish.one(window).on("resize",function(){e.resetPosition()});e.macth=function(){Z(e.val())};e.hide=function(){i.css("display:none")};e.show=function(){if(i.getCss("display")==="none"){i.css("display:block");
e.resetPosition();I()}};e.setTitle=function(a){S.html(a)};e.val=function(a){if(a!==undefined)h.val(a);else return fish.trim(h.val(a))};e.resetPosition=function(){aa(i,h,G)};e.requestUrl=function(a){if(typeof a==="function")x=a};e.localData=w;return e}})})();
