(function(){fish.extend({mSlider:function(T,M){function U(){for(var e="",n=0;n<f;)e+="<li><img src="+fish.all("a",y[n++]).attr("small")+" /></li>";return e}function N(){for(var e=0,n=m.removeClass("current"),o=0;o<n.length;o++)if(this===n[o])e=o;fish.one(this).addClass("current");E(e)}function E(e){z=b;if(!(a.circle&&A)){b=e;if(!a.circle)if(b>=f)b=0;else if(b<0)b=f-1;d.index=b;d.boundary=b===0?"begin":b===f-K?"end":false;if(b>z){a.beforeNextFn&&typeof a.beforeNextFn==="function"&&a.beforeNextFn(d);
O(a.nextFn)}else if(b<z){a.beforePrevFn&&typeof a.beforePrevFn==="function"&&a.beforePrevFn(d);O(a.prevFn)}}}function P(){a.circle&&A||E(b+1)}function Q(){a.circle&&A||E(b-1)}function F(){p&&clearTimeout(p);p=setTimeout(L,a.moveTime)}function G(){clearTimeout(p)}function O(e){switch(a.aniType){case "slide":if(b>f-1)b=0;if(a.circle&&b<z){for(var n=a.scrollNum,o=0;o<n;o++)fish.one(g).html("top",fish.all(a.content+":last-child",H));g.css(q+":"+-r+"px");r=0}R=a.circle?-r:-b*r;A=g.anim(q+":"+R+"px",300,
function(){if(a.circle)if(b<z){r=h*a.scrollNum;b++}else{var S=a.scrollNum;if(a.direction=="scrollLeft"||a.direction=="scrollTop")for(var B=0;B<S;B++)fish.one(g).html("bottom",fish.all(a.content+":first-child",H));else for(B=0;B<S;B++)fish.one(g).html("top",fish.all(a.content+":last-child",H));g.css(q+":0px");b--;if(b<0)b=f-1}e&&typeof e==="function"&&e(d);A=null});break;case "fade":if(!j||!k){s=fish.one(t[b]);j=l.anim(u,a.fadeTime,function(){l.css("display: none;");j=null;l=s});k=s.css("display:block;").anim(C,
a.fadeTime,function(){k=null})}else{if(j){j.stop();fish.one(j.elem).css("display: none;"+u);j=null}if(k){k.stop();l=fish.one(k.elem);k=null;s=fish.one(t[b]);j=fish.one(l).anim(u,a.fadeTime,function(){l.css("display: none;");j=null;l=s});k=s.css("display:block;").anim(C,a.fadeTime,function(){k=null})}}}if(m){m.removeClass("current");fish.one(m[b]).addClass("current")}}function L(){a.direction=="scrollLeft"||a.direction=="scrollTop"?P():Q();p=setTimeout(L,a.moveTime)}if(this[0]){var a={scrollNum:1,
autoScroll:true,moveTime:3500,direction:"scrollLeft",circle:false,canvas:".mSlider_con ul",content:".mSlider_con li",nav:".mSlider_nav li",showNav:"orange",aniType:"slide",fadeTime:240,arrows:false,arrowTheme:false,prevFn:false,nextFn:false,prevBtn:false,nextBtn:false};fish.lang.extend(a,T);var C,u,v,K=1,R=0,b=0,y=fish.all(a.content,this),f=y.length,g=fish.all(a.canvas,this),H=this,m,A,j,k,h,q,c,r,p,t,l,s,V=f,z,d={};if(a.arrows)if(!a.prevBtn&&!a.nextBtn)switch(a.arrowTheme){default:fish.one(this[0].parentNode).html("top",
'<div id="id_mSlider_prev" class="mSlider_arrow mSlider_prev group_left"><span id="tg_last" class="mSlider_arrow_inner mSlider_prev_inner btn01_a"></span></div>');fish.one(this[0].parentNode).html("bottom",'<div id="id_mSlider_next" class="mSlider_arrow mSlider_next group_right"><span id="tg_next" class="mSlider_arrow_inner mSlider_next_inner btn02_a"></span></div>');w=fish.dom("#tg_last");v=fish.dom("#tg_next")}else{w=(w=fish.dom(a.prevBtn,this))?w:fish.dom(a.prevBtn);v=(v=fish.dom(a.nextBtn,this))?
v:fish.dom(a.nextBtn)}if(a.direction=="x")a.direction="scrollLeft";else if(a.direction=="y")a.direction="scrollTop";switch(a.direction){case "scrollLeft":case "scrollRight":q="left";c="width";h=y.width();K=parseInt(fish.one(g[0].parentNode).width()/h,10);break;case "scrollTop":case "scrollBottom":q="top";c="height";h=y.height();K=parseInt(fish.one(g[0].parentNode).height()/h,10);break;default:q="left";c="width";h=y.width()}r=h*a.scrollNum;a.showNav!=="custom"&&this.css("position:relative;overflow:hidden;");
g.css("position:relative;"+c+":"+(f+1)*h+"px");if(a.aniType==="fade"){if(fish.browser("ms",8)||fish.browser("ms",6)||fish.browser("ms",7)){C="filter:alpha(opacity=100);";u="filter:alpha(opacity=1);"}else{C="opacity:1;";u="opacity:0.01"}g.css(c+":"+h+"px");t=fish.all(a.content,H);t.css("display: none;"+u);l=fish.one(t[0]);l.css("display: block;"+C);t.each(function(e){fish.one(e).css("position: absolute; z-index: "+V--+";top: 0; left: 0;")})}if(a.autoScroll){p=setTimeout(L,a.moveTime);if(a.showNav===
"custom"){fish.all(a.canvas,this).hover(G,F);fish.all(a.userNav,this).hover(G,F)}else this.hover(G,F)}if(a.showNav){c="";var I,x,J,w;switch(a.showNav){case "orange":c+="<ul class='mSlider_nav_orange mSlider_nav'>";for(var i=0,D=f;i<D;i++)c+="<li><a href='javascript:void(0)'>"+(i+1)+"</a></li>";c+="</ul>";this.html("bottom",c);break;case "bottom-green":c='<div class="mSlider_nav_bg"></div><div class="mSlider_nav_bottom_green mSlider_nav clearfix"><div class="holder clearfix">';I=fish.all("a",g);J=
h*a.scrollNum/f+"px";i=0;for(D=f;i<D;i++){x=fish.one(I[i]).attr("title");c+='<a style="width:'+J+';" href="javascript:void(0);" title="'+x+'"><span>'+x+'</span><i class="outter">\u25c6</i></a>'}c+="</div></div>";this.html("bottom",c);a.nav=".mSlider_nav a";break;case "earth-yellow":c='<div class="mSlider_nav_bg"></div><div class="mSlider_nav_earth_yellow mSlider_nav clearfix"><div class="holder clearfix">';I=fish.all("a",g);J=h*a.scrollNum/f+"px";i=0;for(D=f;i<D;i++){x=fish.one(I[i]).attr("title");
c+='<a style="width:'+J+';" href="javascript:void(0);" title="'+x+'"><span>'+x+'</span><i class="outter">\u25c6</i></a>'}c+="</div></div>";this.html("bottom",c);a.nav=".mSlider_nav a";break;case "thumbnail":c+="<ul class='mSlider_nav_thumbnail mSlider_nav clearfix'>";c+=U();c+="</ul>";this.html("bottom",c);break;case "custom":a.nav=a.userNav}m=a.userNav?fish.all(a.nav):fish.all(a.nav,this);if(a.showNav==="thumbnail")m.hover(N,function(){});else m.on("mouseover",N)}fish.one(m).addClass("current");
d.startScroll=F;d.stopScroll=G;d.scrollTo=E;d.scrollNext=P;d.scrollPrev=Q;d.boundary="begin";d.index=0;if(w&&v){fish.one(w).on("click",function(){!a.circle&&d.boundary==="begin"||d.scrollPrev()});fish.one(v).on("click",function(){!a.circle&&d.boundary==="end"||d.scrollNext()})}M&&M(d);return d}}})})();
