(function(){fish.extend({autoComplete:function(b){function I(){if(!J){var a=document.createElement("iframe");a.id="mNotice-backdrop";fish.one(i).html("top",a);fish.one(a).css("position:absolute;border:none;filter:alpha(opacity=0);opacity:0;z-index:-1");J=a}a=fish.one(i).width();var d=fish.one(i).height();fish.all(J).css("width:"+a+"px;height:"+d+"px")}function ca(a){y&&clearTimeout(y);y=setTimeout(function(){if(h.ajaxObj)try{h.ajaxObj.abort()}catch(d){}h.ajaxObj=fish.ajax({url:a,type:K,fn:function(c){V(c);
c=W(c);h.origin=e.val();if(c&&c.length){e.setTitle(L);M(c)}else{N&&M();c="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(e.val());e.setTitle(c)}I()}});y=null},200)}function M(a,d){a&&A&&A.call(e,a);p=a;var c;X(j);if(a&&a.length){for(n=0;n<a.length;n++){row=j.insertRow(-1);cell=row.insertCell(-1);c=O.call(row,a[n],n);row.className=l;if(c)row.className+=" "+t;c=B.call(row,a[n],n);if(c===false)j.deleteRow(-1);else cell.innerHTML=P.call(row,a[n],n)?z(c,d):c}if(j.index!==-1){for(c=fish.all("."+l,
j);c[j.index]&&!fish.one(c[j.index]).hasClass(t);)j.index++;if(c[j.index])fish.one(c[j.index]).addClass(q);else j.index=-1}}}function Y(a){var d=[],c,f,g,k,m,u,o,r,C,Z;r=w.length;for(o=0;o<r;o++){c=w[o];f=c.match;Z=f.length;k=-1;for(C=0;C<Z;C++){g=f[C];if(Q)g=g.toLowerCase();if((m=g.indexOf(a))>-1&&(k===-1||m<k)){k=m;u=g}}if(k>-1){D&&D(c,u,k);d[d.length]=c}}if(d.length)d.matchLength=a.length;else{a=a.substr(0,a.length-1);if(a!=="")d=Y(a);d.matchFalid=true}return d}function $(a){var d;if(Q)a=a.toLowerCase();
d=Y(a);h.origin=a;if(d.length){E&&d.sort(E);F&&d.splice(F,d.length);if(d.matchFalid){var c="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(a);e.setTitle(c)}else e.setTitle(L);M(d,a.substr(0,d.matchLength))}else{a="\u5bf9\u4e0d\u8d77\uff0c\u627e\u4e0d\u5230\uff1a"+z(a);e.setTitle(a);X(j)}I()}function z(a,d){if(da){var c=d?d:e.val(),f=RegExp(c,"g"+(Q?"i":""));return a.replace(/(>|^)([^>^<]+)(<|$)/g,function(g){return g.replace(f,function(k){return'<span class="'+aa+'">'+k+"</span>"})})}else return a}
function ba(a,d,c){if(a&&a[0].nodeType===1&&d&&d[0].nodeType===1){var f=fish.one(window).width();fish.one(window).height();var g=d.width(),k=d.height(),m=a.width();a.height();d=d.offset();fish.one(document).scrollTop();var u=fish.one(document).scrollLeft(),o;if(o=c){var r;a:{for(r in c){r=false;break a}r=true}o=!r}if(o){c.x=typeof c.x==="number"?c.x:0;c.y=typeof c.y==="number"?c.y:0}else c={x:0,y:0};d.left-u>f-(d.left-u)&&f-(d.left-u)<m?a.css("left:"+(d.left+g-m-c.x)+"px"):a.css("left:"+(d.left+c.x)+
"px");a.css("top:"+(d.top+k+c.y)+"px")}else throw Error("\u9700\u8981\u6307\u5b9a\u8f93\u5165\u57df\u548c/\u6216\u53ca\u5176\u5f39\u6846\uff01");}function X(a){a.index=ea;for(var d=fish.all("."+l,a).length;d-- >0;)a.deleteRow(-1)}var h,R=fish.guid(),i,S,w=[],p={},G={x:0,y:0},L="\u8f93\u5165\u4e2d\u6587/\u62fc\u97f3/\u2191\u2193\u952e\u9009\u62e9",e={},D=null,E=null,H,da=true,F=10,ea=0,N=false,x="",K="get",Q=true,A,W=function(){},B=function(){},s=function(){},O=function(){return true},V=function(){},
P=function(){return true},v=false,j,J,l="autofill_item",t="enableListRow",q="autofill_hover",aa="autofill_hili",T="autofill_empty",U=false;h=this;if(!h[0])throw Error("autoComplete init faild, fish obj was null when exec fish.all('...').autoComplete()");fish.one("body").html("top",'<div id="autoComplete-'+R+'" class="autofill_wrap"><table class="autofill_tray" cellpadding="0" cellspacing="0"><tr class="autofill_title"><th class="autofill_hd"><span class="autofill_hd_inner"></span></th></tr></table><span class="autofill_close"></span></div>');
i=fish.one("#autoComplete-"+R);S=fish.one(".autofill_hd_inner",i[0]);j=fish.dom(".autofill_tray",i[0]);G.x=b.offsetX!==undefined?b.offsetX:0;G.y=b.offsetY!==undefined?b.offsetY:0;if(typeof b.processAjaxDataFn==="function")W=b.processAjaxDataFn;if(typeof b.itemPrintFn==="function")B=b.itemPrintFn;if(typeof b.template==="string"&&fish.trim(b.template).length)R=b.template;if(typeof b.title==="string"&&fish.trim(b.title).length){L=b.title;S.html(b.title)}typeof b.theme==="string"&&fish.trim(b.theme).length&&
i.addClass(b.theme);if(typeof b.itemClass==="string"&&fish.trim(b.itemClass).length)l=b.itemClass;if(typeof b.highlightClass==="string"&&fish.trim(b.highlightClass).length)aa=b.highlightClass;if(typeof b.emptyClass==="string"&&fish.trim(b.emptyClass).length)T=b.emptyClass;if(typeof b.ajaxFn==="function")V=b.ajaxFn;H=b.width?b.width:H;A=b.processPrintDataFn?b.processPrintDataFn:A;D=b.preSortFn?b.preSortFn:D;F=b.max?b.max:F;E=b.sortFn?b.sortFn:E;N=b.keepListOnNoResult?b.keepListOnNoResult:N;x=b.requestUrl?
b.requestUrl:x;K=b.requestType?b.requestType:K;B=b.itemPrintFn?b.itemPrintFn:B;O=b.itemEnableFn?b.itemEnableFn:O;s=b.itemValueFn?b.itemValueFn:s;w=b.localData?b.localData:w;P=b.itemHighlightFn?b.itemHighlightFn:P;U=b.fillWhenHover!=undefined?b.fillWhenHover:U;H&&fish.all(j).css("width:"+H+"px");ba(i,h,G);i.css("display:none");i.effect({elem:h,interShow:false});var y;h.on("keyup",function(a){fish.getTarget(a);var d;a=fish.getEvent(a);d=a.which?a.which:a.keyCode;a=j;var c;c=e.val();if(c===""||c===b.placeholder)e.hide();
else{e.show();if(d===13){d=fish.all("."+l,a);b.submit&&b.submit(e);if(p[a.index]){h.val(s.call(d[a.index],p[a.index],a.index));b.selectItemFn&&typeof b.selectItemFn=="function"&&b.selectItemFn(h,d[a.index])}e.hide()}else if(d===40||d===38){c=h;var f=fish.all("."+l,a),g=f.length-1;if(f.length){f.removeClass(q);switch(d){case 40:do a.index++;while(f[a.index]&&!fish.one(f[a.index]).hasClass(t));if(a.index>g){a.index=-1;c.val(c.origin)}else{fish.one(f[a.index]).addClass(q);c.val(s.call(f[a.index],p[a.index],
a.index))}break;case 38:do a.index--;while(f[a.index]&&!fish.one(f[a.index]).hasClass(t));if(a.index===-1)c.val(c.origin);else{if(a.index<-1)a.index=g;fish.one(f[a.index]).addClass(q);c.val(s.call(f[a.index],p[a.index],a.index))}}}}else(a=x&&x.call(e,c))?ca(a):$(c)}});i.on("mouseover",function(a){var d=fish.getTarget(a),c,f,g=j;for(f=fish.all("."+l,g);d!==null;){c=fish.one(d);if(c.hasClass(l)){f.removeClass(q);f.each(function(k,m){if(k===d&&fish.one(d).hasClass(t)){c.addClass(q);g.index=m;U&&h.val(s.call(f[g.index],
p[g.index],g.index));return false}});break}d=d.parentNode}});i.on("click",function(a){var d=fish.getTarget(a),c,f,g=j;for(f=fish.all("."+l,g);d!==null;){c=fish.one(d);if(c.hasClass(l)){f.each(function(k,m){if(k===d&&fish.one(d).hasClass(t)){c.addClass(q);g.index=m;h.val(s.call(f[g.index],p[g.index],g.index));b.selectItemFn&&typeof b.selectItemFn=="function"&&b.selectItemFn(h,f[g.index]);return false}});e.hide();break}d=d.parentNode}});fish.one(".autofill_close",i).on("click",function(){e.hide()});
h.on("mousedown",function(){v=true});h.on("mouseup",function(){v=false});i.on("mousedown",function(){v=true});i.on("mouseup",function(){v=false});h.on("focus",function(a){a=fish.getTarget(a);if(fish.trim(a.value)===b.placeholder){a.value="";fish.one(a).removeClass(T)}});h.on("blur",function(a){a=fish.getTarget(a);if(!fish.trim(a.value)||fish.trim(a.value)===b.placeholder){a.value=b.placeholder;fish.one(a).addClass(T)}setTimeout(function(){if(!v){e.hide();v=false}},0)});fish.one(window).on("resize",
function(){e.resetPosition()});e.macth=function(){$(e.val())};e.hide=function(){i.css("display:none")};e.show=function(){if(i.getCss("display")==="none"){i.css("display:block");e.resetPosition();I()}};e.setTitle=function(a){S.html(a)};e.val=function(a){if(a!==undefined)h.val(a);else return fish.trim(h.val(a))};e.resetPosition=function(){ba(i,h,G)};e.requestUrl=function(a){if(typeof a==="function")x=a};e.localData=w;return e}})})();
