(function(){function N(a){var b=a.eachW+2;t=b*7+a.eachCalMargin-2;z=(a.eachH+3)*6+50+2;A=b*2.5-23;J=b*2.5;y=(t+10)*a.monthNum-10}function G(a,b){var c,d;N(a);var l=a.inputElem,g,n;if(l){if((c=l.getAttribute("data-mcalId"))==null){l.setAttribute("data-mcalId",++K);a.mCalId=K;var f=document.createElement("div");g=document.createElement("iframe");var h=document.createElement("div");n=document.createElement("div");var i="",q="",r="<div class = 'top'>",u="";f.id="mCalendar"+a.mCalId;f.onselectstart=function(){return false};
document.body.insertBefore(f,document.body.firstChild);g.className="if";g.src="http://img1.40017.cn/cn/new_ui/public/images/png_cover.png";g.style.cssText="width:"+y+"px;height:"+z+"px;";f.appendChild(g);h.className="date";f.appendChild(h);h.appendChild(n);n.className="top";g=0;for(n=a.monthNum;g<n;g++){if(g==0&&n==1){i=B("one");q=C("first")}else if(g==0){i=B("first");q=C("first")}else if(g==n-1){i=B("last");q=C("last")}else{i=B("mcal"+g,g);q=C("mcal"+g)}r+=i;u+=q}r+="</div>";h.innerHTML=r+u;fish.one(h).css("width:"+
y+"px;");a.calElem=f;f.className="mCalendar";fish.all(a.calElem).css("display:none;")}if(!a.calElem&&(d=fish.all("#mCalendar"+c)).length)a.calElem=d;fish.dom("#mCalendar"+a.mCalId+" .date_lastSpan").onclick=function(){a._DFirstDrawTime=fish.parseDate(a._DFirstDrawTime,{months:-a.monthNum});H(a)};fish.dom("#mCalendar"+a.mCalId+" .date_nextSpan").onclick=function(){a._DFirstDrawTime=fish.parseDate(a._DFirstDrawTime,{months:a.monthNum});H(a)};if(!l.bindCal){c=fish.all(l);if(a.elem){c[all.length]=a.elem;
c.length++}c[c.length]=fish.dom(".date",a.calElem);c.length++;var v=function(){a.time="";G(a,true)};fish.all(c).on("focus",v);fish.all(c).on("blur",function(){setTimeout(function(){w||D(a);w=false},0);this.value=fish.parseTime(this.value)});fish.all(c).on("mousedown",function(s){w=true;fish.preventDefault(s);v();fish.stopBubble(s)});fish.one("body").on("mousedown",function(s){if(w)w=false;else{var o=fish.one(fish.getTarget(s)).getParent(".mCalendar"),E=fish.one(o).getParent(".mCalendar");l!=fish.dom(fish.getTarget(s))&&
o!=a.calElem&&E&&D(a)}});l.bindCal=true}if(a.calElem){a.calElem.className="mCalendar"+(a.css?" "+a.css:"");a._lastTime=a.time=l.value=fish.parseTime(a.time?a.time:l.value);a._DFirstDrawTime=fish.parseDate(a._lastTime);a._DFirstDrawTime.setDate("1");c=parseInt(a.time.split("-")[1],10);a._addNum=c&&!(c%2)?-1:0;if(b){H(a);if(a.pop)fish.require("mPop",function(){if(fish.all(a.calElem).getCss("display")!=="block"){fish.all(a.calElem).css("display:block;");fish.mPop({content:a.calElem,beforClose:function(){fish.all(a.calElem).css("display:none;")}})}});
else{c=fish.one(l).offset();d=fish.one(l).height();f=fish.one(window).width();f=f-c.left>=y+20?c.left:c.left-20-(y-(f-c.left));fish.all(a.calElem).css("top:"+(c.top+d)+"px; left:"+f+"px;");fish.all(a.calElem).css("display:block;")}}}}}function B(a,b){var c=fish.browser("webkit")?"webkit_nextMonth":"nextMonth",d="<div class = 'floatL' style = 'width:"+t+"px;'>";if(a=="one")return d+"<span class='lastMonthBg date_lastSpan'><span class='lastMonth'></span></span><span class='nextMonthBg date_nextSpan'><span class='"+
c+"' ></span></span><h4 class='lastText mCalTitleFir'  style = 'margin-left:"+A+"px;'>xxxx\u5e74xx\u6708</h4></div>";else if(a=="first")return d+"<span class='lastMonthBg date_lastSpan'><span class='lastMonth'></span></span><h4 class='lastText  mCalTitleFir'  style = 'margin-left:"+A+"px;'>xxxx\u5e74xx\u6708</h4></div>";else if(a=="last"){d="<div class = 'floatL' style = 'width:"+t+"px;margin-left:10px'>";return d+"<span class='nextMonthBg date_nextSpan' ><span class='"+c+"' ></span></span><h4 class='nextText  mCalTitleLast' style = 'margin-left:"+
A+"px;'>xxxx\u5e74xx\u6708</h4></div>"}else{d="<div class = 'floatL' style = 'width:"+t+"px;margin-left:10px'>";return d+"<span class='nomalMonthBg'></span><h4 class='normalText mCalTitleMid"+b+"' style = 'margin-left:"+J+"px;'>xxxx\u5e74xx\u6708</h4></div>"}}function C(a){var b="";if(a=="first"){b="<div class = 'contentTime1 contentTime clearfix'>";b+="<table cellspacing='0' cellpadding='0' class='tbl_lastMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg none' >1</i>"}else if(a==
"last"){b="<div class = 'contentTime2 contentTime clearfix'>";b+="<table cellspacing='0' cellpadding='0' class='tbl_nextMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg none'>12</i>"}else{b="<div class = 'contentTimeMiddle contentTime clearfix'>";b+="<table cellspacing='0' cellpadding='0' class="+a+" border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg none' >1</i>"}b+=
"</div>";return b}function F(a,b,c,d,l){var g=fish.dom(a),n=fish.dom(d),f=g.parentNode.getElementsByTagName("i"),h=c.getFullYear(),i=c.getMonth()+1,q=c.getDay(),r=new Date,u=r.getFullYear(),v=r.getMonth()+1;r=r.getDate();var s=0,o=b.ajaxUrl;if(!l)if(b.processData&&b.makeItemView&&typeof o=="string"&&typeof b.processData=="function"){o=o.replace("{year}",h);o=o.replace("{month}",i);fish.ajax({url:o,type:"json",fn:function(x){x=b.processData(x);F(a,b,c,d,x)}});return}b.isDebuge&&c.getDate()!=1&&console.error("\u4f20\u5165\u7684DDrawDate\u7684\u5fc5\u987b\u4e3a\u5f53\u6708\u7684\u7b2c\u4e00\u5929\uff01\uff01\uff01");
o=g.getAttribute("inited")=="true";if(f.length>0){f[0].innerHTML=parseInt(i,10);fish.one(f[0]).css("height:"+z+"px;width:"+t+"px;margin-top:-"+(z/2+40)+"px;");fish.one(f[0]).removeClass("none")}n.innerHTML=h+"\u5e74"+i+"\u6708";var E;n=O(c);if(q!=7)n+=q;var L;if(o){L=fish.all("tr",g);tds=fish.all("td",g);items=fish.all(".itemWrap",g)}for(f=1;f<=42;f++){var p=f-q;if(f%7==1)E=o?L[parseInt(f%7,10)]:g.insertRow(g.rows.length);var j,k;if(o){j=tds[f-1];e=items[f-1];k=fish.dom(".dateWrap",e);k.className=
"dateWrap";e.className="itemWrap"}else{j=E.insertCell(f%7-1);j.innerHTML="";var e=document.createElement("div");k=document.createElement("span");var m=document.createElement("div");k.className="dateWrap";e.className="itemWrap";m.className="useWrap";e.style.cssText="height:"+b.eachH+"px;width:"+b.eachW+"px;float:left;display:inline;overflow:hidden;";j.appendChild(e);e.appendChild(k);e.appendChild(m)}if(q!=7&&f<=q||f>n){k.innerHTML="";fish.one(".useWrap",e).html("");j.className="td02";e.className="spanOut itemWrap";
e.onmouseover=e.onmouseout=e.onclick=null}else{j.className="td01";j=P(h,i,p);if(j==-1){k.innerHTML=p;e.className+=" spanOut";e.setAttribute("s","false");e.setAttribute("d",p)}else{k.innerHTML="";k.className=k.className+" "+j.className;e.className+=" spanOut";e.setAttribute("s","true");e.setAttribute("r",e.className);e.setAttribute("d",j.day)}b.makeItemView&&typeof b.makeItemView=="function"&&l&&fish.one(".useWrap",e).html(makeItemFn(h,i,p,l[s++]));i<10?e.setAttribute("m",h+"-0"+i):e.setAttribute("m",
h+"-"+i);e.onmouseover=function(){if(this.getAttribute("s")=="true")this.className=this.getAttribute("r")+" hover";else fish.one(this).addClass("spanHover")};e.onmouseout=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r"):"itemWrap spanOut"};j=false;if(u>h)j=true;else if(u==h)if(v>i)j=true;else if(v==i)if(r>p)j=true;if(b.endTime){m=b.endTime.split("-");if(m.length>0)if(parseInt(m[0])<h)j=true;else if(parseInt(m[0])==h)if(parseInt(m[1],10)<i)j=true;else if(parseInt(m[1],
10)==i)if(parseInt(m[2],10)<p)j=true}if(b.startTime){m=b.startTime.split("-");if(m.length>0)if(parseInt(m[0])>h)j=true;else if(parseInt(m[0])==h)if(parseInt(m[1],10)>i)j=true;else if(parseInt(m[1],10)==i)if(parseInt(m[2],10)>=p)j=true}if(j&&!b.showPast){e.className="itemWrap spanOver";k.className="dateWrap";if(k.innerHTML=="")k.innerHTML=e.getAttribute("d");e.onmouseover=e.onmouseout=e.onclick=null}else e.onclick=function(){var x=this.getAttribute("m"),I=this.getAttribute("d")?this.getAttribute("d"):
this.innerHTML;b._lastTime=x+"-"+I;if(parseInt(I,10)<=9)b._lastTime=x+"-0"+I;b.inputElem.value=b._lastTime;b.inputElem&&b.showDay&&Q(b.inputElem,b._lastTime,b);D(b,function(){b.fn&&b.fn(b._lastTime)})};if(u==h&&v==i&&r==p){k.innerHTML="";k.className="spanDay dateWrap";e.setAttribute("d",p);e.setAttribute("s","true");e.setAttribute("r",e.className)}if(fish.parseTime(h+"-"+i+"-"+p)==fish.parseTime(new Date,{days:1})){k.innerHTML="";k.className="spanTomo dateWrap";e.setAttribute("s","true");e.setAttribute("d",
p);e.setAttribute("r",e.className)}if(b._lastTime!=null){k=b._lastTime.split("-")[0];j=b._lastTime.split("-")[1];m=b._lastTime.split("-")[2];if(R(new Date(k,j,m),new Date(h,i,p),b)){e.className=e.getAttribute("s")=="true"?e.getAttribute("r")+" clickDate":"clickDate itemWrap";e.onmouseout=function(){this.className=this.getAttribute("s")=="true"?this.getAttribute("r")+" clickDate":"clickDate itemWrap"}}}e.className+=" dateWrap"}}g.setAttribute("inited","true")}function D(a,b){if(a.pop)fish.require("mPop",
function(){fish.mPop.close()});else a.calElem.style.display="none";b&&b();w=false}function M(a){a=a||{};var b={css:"",time:"",open:false,startTime:"",endTime:"",inputElem:this[0],showPast:false,fn:null,calElem:null,_lastTime:null,fontSize:12,_DFirstDrawTime:null,eachH:30,eachW:30,eachCalMargin:10,monthNum:2,showDay:false,isAjax:false,ajaxFn:false};if(b.inputElem&&b.inputElem.getAttribute("data-mcalid")!=null)b.mCalId=b.inputElem.getAttribute("data-mcalid");fish.lang.extend(b,a);G(b,b.open);return{setAjaxUrl:function(c){b.ajaxUrl=
c}}}function R(a,b,c){var d=new Date;if(c.startTime){d=c.startTime;if(typeof d!="string")d=new Date;else{d=d.replace(/-/g,"/");d=new Date(Date.parse(d))}}else d=new Date(d.getFullYear(),d.getMonth(),d.getDate());if(a-b===0)if(c.showPast)return true;else if(a-d>=0)return true;return false}function P(a,b,c){var d={specialDate:[{date:"2011-01-01",name:"\u5143\u65e6",className:"yuandan"},{date:"2011-12-25",name:"\u5723\u8bde\u8282",className:"\u5723\u8bde"},{date:"2012-01-01",name:"\u5143\u65e6",className:"yuandan"},
{date:"2012-02-22",name:"\u9664\u5915",className:"chuxi"},{date:"2012-04-04",name:"\u6e05\u660e",className:"qingming"},{date:"2012-05-01",name:"\u52b3\u52a8\u8282",className:"wuyi"},{date:"2012-06-01",name:"\u513f\u7ae5\u8282",className:"liuyi"},{date:"2012-06-23",name:"\u7aef\u5348",className:"duanwu"},{date:"2012-08-23",name:"qixi",className:"qixi"},{date:"2012-09-30",name:"\u4e2d\u79cb",className:"zhongqiu"},{date:"2012-10-01",name:"\u56fd\u5e86",className:"guoqing"},{date:"2012-12-25",name:"\u5723\u8bde",
className:"shendan"},{date:"2013-01-01",name:"\u5143\u65e6",className:"yuandan"}]};a:{a=new Date(a,b-1,c);if(d){d=d.specialDate;var l,g;c=-1;c=0;for(l=d.length;c<l;c++){b=d[c];g=b.date;var n=g=new Date(g.replace(/-/g,"/")),f=a;n.getFullYear();n.getMonth();n.getDate();f.getFullYear();f.getMonth();f.getDate();var h=false;if(n.getTime()==f.getTime())h=true;if(h){c={};c.name=b.name;c.className=b.className;c.day=g.getDate()+"";a=c;break a}}}a=-1}return a}function H(a){var b=a._DFirstDrawTime,c,d;c=0;for(d=
a.monthNum;c<d;c++){if(c==0)F("#mCalendar"+a.mCalId+" .tbl_lastMonth",a,b,"#mCalendar"+a.mCalId+" .mCalTitleFir");else c==d-1?F("#mCalendar"+a.mCalId+" .tbl_nextMonth",a,b,"#mCalendar"+a.mCalId+" .mCalTitleLast"):F("#mCalendar"+a.mCalId+" .mcal"+c,a,b,"#mCalendar"+a.mCalId+" .mCalTitleMid"+c);b=fish.parseDate(b,{months:1})}}function O(a){a=new Date(a);a.setMonth(a.getMonth()+1);a.setDate(0);return a.getDate()}function Q(a,b,c){b=fish.parseDate(b).getDay();var d=fish.one(".mCalendar"+c.mCalId);a=fish.one(a);
if(d.length==0){d=fish.one(document.createElement("div"));d.addClass("dayWrap");d.addClass("mCalendar"+c.mCalId);d.css("height:"+a.height()+"px;line-height:"+a.height()+"px;left:"+(a.offset().left+a.width()-52)+"px;top:"+a.offset().top+"px;font-size:"+S(a)+";");document.body.appendChild(d[0]);d.on("click",function(){c.time="";G(c,true)})}switch(b){case 1:b="\u4e00";break;case 2:b="\u4e8c";break;case 3:b="\u4e09";break;case 4:b="\u56db";break;case 5:b="\u4e94";break;case 6:b="\u516d";break;case 0:b=
"\u65e5"}d.html("\u661f\u671f"+b)}function S(a){try{return fish.one(a).getCss("font-size")}catch(b){return 12}}var t=223,y,z=223,A,J,K=0,w;M.close=D;fish.extend({mCal:M,preventInput:function(a){fish.all(a?a:this).each(function(b){if(!b.getAttribute("_preventInput_")){b.style.imeMode="disabled";b.onkeydown=function(c){fish.preventDefault(c)};b.oncontextmenu=function(){return false};b.onselectstart=function(){return false};b.setAttribute("_preventInput_","true")}})},recoverInput:function(a){fish.all(a?
a:this).each(function(b){if(b.getAttribute("_preventInput_")){b.style.imeMode="";b.onkeydown=b.oncontextmenu=b.onselectstart=null;b.setAttribute("_preventInput_","")}})}})})();
