(function(){function s(a,b,e){x.hasCallOnce=false;return x(a,b,e)}function x(a,b,e){if(typeof a==="object")var c=a.getFullYear(),g=a.getMonth()+1,f=a.getDate(),k=a.getHours(),i=a.getMinutes(),d=a.getSeconds();else{d=(a?a:"").split("-");c=parseInt(d[0],10);g=parseInt(d[1],10);f=parseInt(d[2],10);k=i=d=0}var n=new Date,h={years:0,months:0,days:0,hours:0,minutes:0,seconds:0,timeMode:null};if(c&&g&&f){fish.lang.extend(h,b);c+=h.years;g+=h.months;f+=h.days;k+=h.hours;i+=h.minutes;d+=h.seconds;d=new Date(c,
g-1,f,k,i,d);c=d.getFullYear();g=d.getMonth()+1;f=d.getDate();k=d.getHours();i=d.getMinutes();d=d.getSeconds();g=g<10?"0"+g:g;f=f<10?"0"+f:f;k=k<10?"0"+k:k;i=i<10?"0"+i:i;d=d<10?"0"+d:d;h=h.timeMode?h.timeMode.replace("YYYY",c).replace("MM",g).replace("DD",f).replace("hh",k).replace("mm",i).replace("ss",d):[c,g,f].join("-");return h=e?{y:c,m:g,d:f,h:k,mi:i,s:d}:h}else if(!arguments.callee.hasCallOnce){arguments.callee.hasCallOnce=true;return arguments.callee([n.getFullYear(),n.getMonth()+1,n.getDate()].join("-"),
b,e)}}function y(a){fish.all(a?a:this).each(function(b){if(!b.getAttribute("_preventInput_")){b.style.imeMode="disabled";b.onkeydown=function(e){fish.preventDefault(e)};b.oncontextmenu=function(){return false};b.onselectstart=function(){return false};b.setAttribute("_preventInput_","true")}})}function z(a,b){var e=fish.dom(a.inputElem);if(e){y(e);if(v)a.calElem=v;else{var c=document.createElement("div");c.id="mCalendar";c.onselectstart=function(){return false};document.body.appendChild(c);var g=document.createElement("iframe");
g.className="if";c.appendChild(g);g=document.createElement("div");g.className="date";c.appendChild(g);var f=document.createElement("div");g.appendChild(f);f.className="top";var k=fish.browser("webkit")?"webkit_nextMonth":"nextMonth";f.innerHTML="<span class='lastMonthBg' id='date_lastSpan'><span class='lastMonth' ></span></span><h4 class='lastText' id='tbl_lastMonth_input'>xxxx\u5e74xx\u6708</h4><span class='nextMonthBg' id='date_nextSpan'><span class='"+k+"' ></span></span><h4 class='nextText' id='tbl_nextMonth_input'>xxxx\u5e74xx\u6708</h4>";
f=document.createElement("div");f.className="contentTime1";f.innerHTML="<table cellspacing='0' cellpadding='0' id='tbl_lastMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg' >1</i>";g.appendChild(f);f=document.createElement("div");f.className="contentTime2";f.innerHTML="<table cellspacing='0' cellpadding='0' id='tbl_nextMonth' border='0'><tbody><tr><th>\u65e5</th><th>\u4e00</th><th>\u4e8c</th><th>\u4e09</th><th>\u56db</th><th>\u4e94</th><th>\u516d</th></tr></tbody></table><i class='monthBg'>12</i>";
g.appendChild(f);a.calElem=v=c;c.className="mCalendar";fish.all(a.calElem).css("display:none;")}fish.dom("#date_lastSpan").onclick=function(){var d=a.inputElem._mCalDate_;d._addNum-=4;o("#tbl_lastMonth",d);o("#tbl_nextMonth",d)};fish.dom("#date_nextSpan").onclick=function(){var d=a.inputElem._mCalDate_;o("#tbl_lastMonth",d);o("#tbl_nextMonth",d)};if(!a.inputElem.bindCal){var i;if(a.elem){i=fish.all(a.elem);i[i.length]=a.inputElem;i.length++}c=i?i:a.inputElem;fish.one(a.calElem).effect({elem:c,type:"click",
interFn:function(){var d=a.inputElem._mCalDate_;d.time="";z(d,true)}});a.inputElem.bindCal=true}a.calElem.className="mCalendar"+(a.css?" "+a.css:"");a._lastTime=a.time=e.value=s(a.time?a.time:e.value);c=parseInt(a.time.split("-")[1],10);a._addNum=c&&!(c%2)?-1:0;A=a.inputElem._mCalDate_=a;if(b){o("#tbl_lastMonth",a);o("#tbl_nextMonth",a);c=fish.one(e).offset();e=fish.one(e).height();fish.all(a.calElem).css("top:"+(c.top+e)+"px; left:"+c.left+"px;");w(function(){fish.all(a.calElem).css("display:block;")})}else a._addNum+=
2}}function o(a,b){for(var e=fish.dom(a),c=fish.dom(a+"_input"),g=e.parentNode.getElementsByTagName("i");e.rows.length>1;)e.deleteRow(1);var f=s(b.time.split("-")[0]+"-"+b.time.split("-")[1]+"-01",{months:b._addNum}).split("-");if(g.length>0)g[0].innerHTML=parseInt(f[1],10);c.innerHTML=f[0]+"\u5e74"+f[1]+"\u6708";c=f[0]+"-"+f[1]+"-1";b._addNum++;c=new Date(Date.parse(c.replace(/-/g,"/")));g=c.getDay();c.setMonth(c.getMonth()+1);c.setDate(0);var k,i=c.getDate(0);if(g!=7)i+=g;for(var d=1;d<=42;d++){var n=
d-g;if(d%7==1)k=e.insertRow(e.rows.length);if(g!=7&&d<=g){var h=k.insertCell(d%7-1);h.innerHTML="  ";h.className="td02";var j=document.createElement("span");j.innerHTML=" ";j.className="spanOut"}else if(d>i){h=k.insertCell(d%7-1);h.innerHTML="  ";h.className="td02";j=document.createElement("span");j.innerHTML=" ";j.className="spanOut"}else{h=k.insertCell(d%7-1);h.className="td01";j=document.createElement("span");j.innerHTML=n;j.setAttribute("m",f[0]+"-"+f[1]);j.className="spanOut";j.onmouseover=function(){this.className=
"spanHover"};j.onmouseout=function(){this.className="spanOut"};var m=false,t=c.getFullYear(),u=c.getMonth();c.getDate();var p=new Date,q=p.getFullYear(),r=p.getMonth();p=p.getDate();if(q>t)m=true;else if(q==t)if(r>u)m=true;else if(r==u)if(p>n)m=true;if(b.endTime){var l=b.endTime.split("-");if(l.length>0)if(parseInt(l[0])<c.getFullYear())m=true;else if(parseInt(l[0])==c.getFullYear())if(parseInt(l[1],10)<c.getMonth()+1)m=true;else if(parseInt(l[1],10)==c.getMonth()+1)if(parseInt(l[2],10)<n)m=true}if(b.startTime){l=
b.startTime.split("-");if(l.length>0)if(parseInt(l[0])>c.getFullYear())m=true;else if(parseInt(l[0])==c.getFullYear())if(parseInt(l[1],10)>c.getMonth()+1)m=true;else if(parseInt(l[1],10)==c.getMonth()+1)if(parseInt(l[2],10)>=n)m=true}if(m&&!b.showPast){j.className="spanOver";j.onmouseover=function(){this.className="spanOver"};j.onmouseout=function(){this.className="spanOver"}}else j.onclick=function(){var B=this.getAttribute("m");b._lastTime=B+"-"+this.innerHTML;if(this.innerHTML.length==1)b._lastTime=
B+"-0"+this.innerHTML;if(b.inputElem)b.inputElem.value=b._lastTime;w(function(){b.fn&&b.fn(b._lastTime)})};if(q==t&&r==u&&p==n){j.className="spanDay";j.onmouseout=function(){this.className="spanDay"}}if(b._lastTime!=null){m=b._lastTime.split("-")[0];q=b._lastTime.split("-")[1];r=b._lastTime.split("-")[2];if(E(new Date(m,q-1,r),new Date(t,u,n),b)){j.className="clickDate";j.onmouseout=function(){this.className="clickDate"}}}}h.appendChild(j)}}function w(a){setTimeout(function(){A.calElem.style.display=
"none";a&&a()},20)}function C(a){var b={css:"",time:"",open:false,startTime:"",endTime:"",inputElem:this[0],showPast:false,fn:null,calElem:null,_lastTime:null,_addNum:0};fish.lang.extend(b,a||{});z(b,b.open)}function D(a,b){var e=a.getFullYear(),c=a.getMonth(),g=a.getDate(),f=b.getFullYear(),k=b.getMonth();b.getDate();return e==f&&c==k&&g==b?0:a.getTime()-b.getTime()}function E(a,b,e){var c;if(e.startTime){c=e.startTime;if(typeof c!="string")c=new Date;else{c=c.replace(/-/g,"/");c=new Date(Date.parse(c))}}else c=
new Date;if(D(a,b)==0)if(e.showPast)return true;else if(D(a,c)>=0)return true;return false}var A,v;C.close=w;fish.extend({mCal:C,preventInput:y,recoverInput:function(a){fish.all(a?a:this).each(function(b){if(b.getAttribute("_preventInput_")){b.style.imeMode="";b.onkeydown=b.oncontextmenu=b.onselectstart=null;b.setAttribute("_preventInput_","")}})},parseTime:s,parseDate:function(a,b){var e=s(a,b,true);return new Date(parseInt(e.y,10),parseInt(e.m,10)-1,parseInt(e.d,10),parseInt(e.h,10),parseInt(e.mi,
10),parseInt(e.s,10))}})})();
