(function(d){d.extend({mNotice:function(e){function A(a){var b=true;a=d.all(a);if(a.length){a.each(function(c){if(!(d.one(c).hasClass("none")||c.style.display==="none"))return b=false});return b}else return 1}function B(a){if(a=C.apply(g,[a,D])){f.html("");f.html(a);j=true}else j=false}function E(a,b){var c;L(g);if(c=C.apply(g,[a,D])){f=M(c,b);j=true;F==="mTab"&&N(F,g,b);O(g,f);P&&Q(f,g);if(R){S(f);T(f)}U(g,f);V(f,g);if(d.one(".mNotice-close",f).length)f.on("click",function(l){l=d.getTarget(l);d.one(l).hasClass("mNotice-close")&&
f.addClass("none")})}else j=false}function n(){if(!p){var a=document.createElement("iframe");a.id="mNotice-backdrop";fish.one(f).html("top",a);d.one(a).css("position:absolute;border:none;filter:alpha(opacity=0);opacity:0;z-index:-1");p=a}a=fish.one(f).width();var b=fish.one(f).height();fish.all(p).css("width:"+a+"px;height:"+b+"px")}function M(a,b){f=document.createElement("div");var c=d.one(f);f.id="mNotice-"+b;f.className=G?"mNotice-wrap none "+G:"mNotice-wrap none";c.css("position: absolute; z-index: 1000000;");
document.body.insertBefore(f,document.body.firstChild);f.innerHTML=a;n();return c}function N(a,b,c){a==="mTab"&&d.one("#mNotice-"+c).mTab({tab_tray:".mNotice-mTab-tab-tray",append:"current",content:".mNotice-mTab-content",fn:function(){q();n()}})}function O(a,b){a.on("focus",function(){d.all("body .mNotice-wrap").addClass("none");if(j&&A(H)){b.removeClass("none");m(b,a,o);n()}})}function L(a){a.on("click",function(){a[0].select()})}function Q(a,b){a.on("click",function(c){c=d.getTarget(c);if(d.one(c).hasClass("mNotice-normal")){b.val(c.innerHTML);
b.attr("cid",c.getAttribute("cid"));b.attr("ctype",c.getAttribute("ctype"));b.addClass("color-normal");a.addClass("none");I&&I.apply(d.one(c),[b])}})}function S(a){a.on("mouseover",function(b){b=d.getTarget(b);if(d.one(b).hasClass("mNotice-normal")){d.all(".mNotice-normal",a).removeClass("mNotice-hover");d.one(b).addClass("mNotice-hover")}})}function T(a){a.on("mouseout",function(){d.all(".mNotice-normal",a).removeClass("mNotice-hover")})}function V(a,b){d.one(document).on("click",function(c){for(c=
d.getTarget(c);c!==null;){if(c.nodeType===1&&(c===b[0]||c.className.indexOf("mNotice-wrap")>-1))return;c=c.parentNode}a.addClass("none")})}function U(a,b){a.on("keydown",function(c){c=d.getEvent(c);key=c.keyCode||c.which;typeof key==="number"&&b.addClass("none")})}function m(a,b,c){if(a&&a[0].nodeType===1&&b&&b[0].nodeType===1){a.css("left:-1000px;");c=d.one(window).width();d.one(window).height();var l=b.width(),W=b.height(),J=a.width();a.height();b=b.offset();d.one(document).scrollTop();var r=d.one(document).scrollLeft();
if(i&&!s(i)){i.x=typeof i.x==="number"?i.x:0;i.y=typeof i.y==="number"?i.y:0}else var i={x:0,y:0};b.left-r>c-(b.left-r)&&c-(b.left-r)<J?a.css("left:"+(b.left+l-J-i.x)+"px"):a.css("left:"+(b.left+i.x)+"px");a.css("top:"+(b.top+W+i.y)+"px")}else m(f,g,c)}function q(){if(!(!f||f.hasClass("none"))){t&&clearTimeout(t);t=setTimeout(function(){m(f,g,o);n()},100)}}function s(a){for(var b in a)return false;return true}function K(a){if(!window.iError)window.iError=[];window.iError.push({date:(new Date).toString(),
info:a})}var u=fish.guid();if(!e)throw Error("\u4f20\u9012\u8bbe\u7f6e\u53c2\u6570\uff01");var g=e.beside;if(this.length)g=d.one(this[0]);else{if(!g||typeof g!=="string"&&g.nodeType!==1&&!g.length)throw Error("\u6307\u5b9a\u9700\u8981\u5f39\u6846\u7684\u8282\u70b9\u9009\u62e9\u5668\u6216\u8282\u70b9\uff01");g=d.one(g);if(!g.length)throw Error("\u6307\u5b9a\u9700\u8981\u5f39\u6846\u7684\u8282\u70b9\uff01");}if(!{INPUT:"INPUT",TEXTAREA:"TEXTAREA"}[g[0].nodeName])throw Error("\u6307\u5b9a\u7684\u8f93\u5165\u57df\u65e0\u6548\uff01");
var o={x:0,y:0},v=e.offset&&e.offset.x,w=e.offset&&e.offset.y,h=e.request,k=e.localData,D=typeof e.template==="string"?e.template:undefined,F=e.mode==="mTab"?"mTab":"",p,C=e.display,P=e.isClick===undefined?false:!!e.isClick,R=e.isHover===undefined?false:!!e.isHover,I=typeof e.clickCallback==="function"?e.clickCallback:false,G=typeof e.theme==="string"?e.theme:"",x=typeof e.urlInTime==="function"?e.urlInTime:false,H=typeof e.rejects==="string"?e.rejects:false,y="",f,j,t,z={};if(e.offset&&(parseInt(v)||
parseInt(w))){v&&(o.x=v);w&&(o.y=w)}if(!e.display&&typeof e.display!=="function")throw Error("\u6307\u5b9a\u6570\u636e\u6e32\u67d3\u51fd\u6570\uff01");if(!h&&!k||h&&k)throw Error("\u6307\u5b9a\u552f\u4e00\u6570\u636e\u6e90\uff01");else if(h&&x){y=h.url;h.url=x(y);h.fn=function(a){if(a&&(a.length||!s(a)))d.ready(function(){z[h.url.substring(h.url.indexOf("?")+1)]=a;d.all("#mNotice-"+u).length?B(a):E(a,u)})};h.onTimeout=function(){K("\u670d\u52a1\u5668\u7aef\u54cd\u5e94\u8d85\u65f6\uff01")};h.err=function(){K("\u670d\u52a1\u5668\u7aef\u53d1\u751f\u9519\u8bef\uff01")};
d.ajax(h)}else d.ready(function(){if(k&&(k.length||!s(k)))E(k,u)});d.ready(function(){d.one(window).on("resize",q);d.one(window).on("scroll",q)});return{show:function(){setTimeout(function(){j&&A(H)&&f.removeClass("none")&&m()},0)},hide:function(){f.addClass("none")},position:m,update:function(){var a;h.url=x(y);a=h.url.substring(h.url.indexOf("?")+1);z[a]?B(z[a]):d.ajax(h)}}}})})(fish);
