(function(){fish.extend({mSlider:function(T,K){function U(){for(var d="",j=0;j<e;)d+="<li><img src="+fish.all("a",s[j++]).attr("small")+" /></li>";return d}function L(){for(var d=0,j=i.removeClass("current"),k=0;k<j.length;k++)if(this===j[k])d=k;fish.one(this).addClass("current");n(d)}function n(d){t=b;if(!(a.circle&&u)){b=d;if(!a.circle)if(b>=e)b=0;else if(b<0)b=e-1;if(b>t){a.beforeNextFn&&typeof a.beforeNextFn==="function"&&a.beforeNextFn(l);M(a.nextFn)}else if(b<t){a.beforePrevFn&&typeof a.beforePrevFn===
"function"&&a.beforePrevFn(l);M(a.prevFn)}}}function N(){a.circle&&u||n(b+1)}function O(){a.circle&&u||n(b-1)}function P(){o&&clearTimeout(o);o=setTimeout(H,a.moveTime)}function Q(){clearTimeout(o)}function M(d){switch(a.aniType){case "slide":if(b>e-1)b=0;if(a.circle&&b<t){for(var j=a.scrollNum,k=0;k<j;k++)fish.one(g).html("top",fish.all(a.content+":last-child",I));g.css(p+":"+-q+"px");q=0}R=a.circle?-q:-b*q;u=g.anim(p+":"+R+"px",300,function(){if(a.circle)if(b<t){q=h*a.scrollNum;b++}else{var S=a.scrollNum;
if(a.direction=="scrollLeft"||a.direction=="scrollTop")for(var v=0;v<S;v++)fish.one(g).html("bottom",fish.all(a.content+":first-child",I));else for(v=0;v<S;v++)fish.one(g).html("top",fish.all(a.content+":last-child",I));g.css(p+":0px");b--;if(b<0)b=e-1}d&&typeof d==="function"&&d(l);u=null});break;case "fade":if(!z||!A){J=fish.one(w[b]);z=x.anim(B,a.fadeTime,function(){x.css("display: none;");z=null;x=J;if(m.length&&!A){n(m.pop());m=[]}});A=J.css("display:block;").anim(C,a.fadeTime,function(){A=null;
if(m.length&&!z){n(m.pop());m=[]}})}else m.push(b)}if(i){i.removeClass("current");fish.one(i[b]).addClass("current")}}function H(){a.direction=="scrollLeft"||a.direction=="scrollTop"?N():O();o=setTimeout(H,a.moveTime)}if(this[0]){var a={scrollNum:1,autoScroll:true,moveTime:3500,direction:"scrollLeft",circle:false,canvas:".mSlider_con ul",content:".mSlider_con li",nav:".mSlider_nav li",showNav:"orange",aniType:"slide",fadeTime:100,arrows:false,arrowTheme:false,prevFn:false,nextFn:false,prevBtn:false,
nextBtn:false},C,B;fish.lang.extend(a,T);var D,E;if(a.arrows)if(!a.prevBtn&&!a.nextBtn)switch(a.arrowTheme){default:fish.one(this[0].parentNode).html("top",'<div id="id_mSlider_prev" class="mSlider_arrow mSlider_prev group_left"><span id="tg_last" class="mSlider_arrow_inner mSlider_prev_inner btn01_a"></span></div>');fish.one(this[0].parentNode).html("bottom",'<div id="id_mSlider_next" class="mSlider_arrow mSlider_next group_right"><span id="tg_next" class="mSlider_arrow_inner mSlider_next_inner btn02_a"></span></div>');
D=fish.dom("#tg_last");E=fish.dom("#tg_next")}else{D=fish.dom(a.prevBtn);E=fish.dom(a.nextBtn)}if(fish.browser("ms",8)||fish.browser("ms",6)||fish.browser("ms",7)){C="filter:alpha(opacity=99);";B="filter:alpha(opacity=1);"}else{C="opacity:0.99;";B="opacity:0.01"}var R=0,b=0,s=fish.all(a.content,this),e=s.length,g=fish.all(a.canvas,this),I=this,i,u,z,A,h,p,c,q,o,w,x,J,m=[],V=e,t;if(a.direction=="x")a.direction="scrollLeft";else if(a.direction=="y")a.direction="scrollTop";switch(a.direction){case "scrollLeft":case "scrollRight":p=
"left";c="width";h=s.width();break;case "scrollTop":case "scrollBottom":p="top";c="height";h=s.height();break;default:p="left";c="width";h=s.width()}q=h*a.scrollNum;this.css("position:relative;overflow:hidden;");g.css("position:relative;"+c+":"+(e+1)*h+"px");if(a.aniType==="fade"){g.css(c+":"+h+"px");w=fish.all(a.content);w.css("display: none;"+B);x=fish.one(w[0]);x.css("display: block;"+C);w.each(function(d){fish.one(d).css("position: absolute; z-index: "+V--+";top: 0; left: 0;")})}if(a.autoScroll){o=
setTimeout(H,a.moveTime);this.hover(Q,P)}if(a.showNav){c="";var F,r,G;switch(a.showNav){case "orange":c+="<ul class='mSlider_nav_orange mSlider_nav'>";for(var f=0,y=e;f<y;f++)c+="<li><a href='javascript:void(0)'>"+(f+1)+"</a></li>";c+="</ul>";this.html("bottom",c);break;case "bottom-green":c='<div class="mSlider_nav_bg"></div><div class="mSlider_nav_bottom_green mSlider_nav clearfix"><div class="holder clearfix">';F=fish.all("a",g);G=h*a.scrollNum/e+"px";f=0;for(y=e;f<y;f++){r=fish.one(F[f]).attr("title");
c+='<a style="width:'+G+';" href="javascript:void(0);" title="'+r+'"><span>'+r+'</span><i class="outter">\u25c6</i></a>'}c+="</div></div>";this.html("bottom",c);a.nav=".mSlider_nav a";break;case "earth-yellow":c='<div class="mSlider_nav_bg"></div><div class="mSlider_nav_earth_yellow mSlider_nav clearfix"><div class="holder clearfix">';F=fish.all("a",g);G=h*a.scrollNum/e+"px";f=0;for(y=e;f<y;f++){r=fish.one(F[f]).attr("title");c+='<a style="width:'+G+';" href="javascript:void(0);" title="'+r+'"><span>'+
r+'</span><i class="outter">\u25c6</i></a>'}c+="</div></div>";this.html("bottom",c);a.nav=".mSlider_nav a";break;case "thumbnail":c+="<ul class='mSlider_nav_thumbnail mSlider_nav clearfix'>";c+=U();c+="</ul>";this.html("bottom",c)}i=fish.all(a.nav,this);if(a.showNav==="thumbnail")i.hover(L,function(){});else i.on("mouseover",L)}fish.one(i).addClass("current");var l={startScroll:P,stopScroll:Q,scrollTo:n,scrollNext:N,scrollPrev:O};if(D&&E){fish.one(D).on("click",function(){l.scrollPrev()});fish.one(E).on("click",
function(){l.scrollNext()})}K&&K(l);return l}}})})();
