(function(d){d.extend({mNotice:function(e){function z(a){var b=true;a=d.all(a);if(a.length){a.each(function(c){if(!(d.one(c).hasClass("none")||c.style.display==="none"))return b=false});return b}else return 1}function A(a){if(a=B.apply(f,[a,C])){g.html("");g.html(a);j=true}else j=false}function D(a){K(f);if(a=B.apply(f,[a,C])){g=L(a);j=true;E==="mTab"&&M(E,f);N(f,g);O&&P(g,f);if(Q){R(g);S(g)}T(f,g);U(g,f);if(d.one(".mNotice-close",g).length)g.on("click",function(b){b=d.getTarget(b);d.one(b).hasClass("mNotice-close")&&
g.addClass("none")})}else j=false}function L(a){var b=document.createElement("div"),c=d.one(b);b.id="mNotice-"+f[0].id;b.className=F?"mNotice-wrap none "+F:"mNotice-wrap none";c.css("position: absolute; z-index: 1000000;");document.body.insertBefore(b,document.body.firstChild);b.innerHTML=a;if(d.browser("ms",6)){a=document.createElement("iframe");a.id="mNotice-backdrop";b.insertBefore(a,b.firstChild);d.one(a).css("filter:alpha(opacity=0);")}return c}function M(a,b){a==="mTab"&&d.one("#mNotice-mTab-"+
b[0].id).mTab({tab_tray:".mNotice-mTab-tab-tray",append:"current",content:".mNotice-mTab-content",fn:function(){o()}})}function N(a,b){a.on("focus",function(){d.all("body .mNotice-wrap").addClass("none");if(j&&z(G)){b.removeClass("none");p(b,a,m);d.browser("ms",6)&&H(b)}})}function K(a){a.on("click",function(){a[0].select()})}function P(a,b){a.on("click",function(c){c=d.getTarget(c);if(d.one(c).hasClass("mNotice-normal")){b.val(c.innerHTML);b.attr("cid",c.getAttribute("cid"));b.attr("ctype",c.getAttribute("ctype"));
b.addClass("color-normal");a.addClass("none");I&&I.apply(d.one(c),[b])}})}function R(a){a.on("mouseover",function(b){b=d.getTarget(b);if(d.one(b).hasClass("mNotice-normal")){d.all(".mNotice-normal",a).removeClass("mNotice-hover");d.one(b).addClass("mNotice-hover")}})}function S(a){a.on("mouseout",function(){d.all(".mNotice-normal",a).removeClass("mNotice-hover")})}function U(a,b){d.one(document).on("click",function(c){for(c=d.getTarget(c);c!==null;){if(c.nodeType===1&&(c===b[0]||c.className.indexOf("mNotice-wrap")>
-1))return;c=c.parentNode}a.addClass("none")})}function T(a,b){a.on("keydown",function(c){c=d.getEvent(c);key=c.keyCode||c.which;typeof key==="number"&&b.addClass("none")})}function p(a,b,c){if(a&&a[0].nodeType===1&&b&&b[0].nodeType===1){var l=d.one(window).width();d.one(window).height();var n=b.width(),q=b.height(),i=a.width();a.height();b=b.offset();d.one(document).scrollTop();var r=d.one(document).scrollLeft();if(c&&!s(c)){c.x=typeof c.x==="number"?c.x:0;c.y=typeof c.y==="number"?c.y:0}else c=
{x:0,y:0};b.left-r>l-(b.left-r)&&l-(b.left-r)<i?a.css("left:"+(b.left+n-i-c.x)+"px"):a.css("left:"+(b.left+c.x)+"px");a.css("top:"+(b.top+q+c.y)+"px")}else throw Error("\u9700\u8981\u6307\u5b9a\u8f93\u5165\u57df\u548c/\u6216\u53ca\u5176\u5f39\u6846\uff01");}function o(){if(!(!g||g.hasClass("none"))){t&&clearTimeout(t);t=setTimeout(function(){p(g,f,m);d.browser("ms",6)&&H(g)},100)}}function H(){var a,b;a=function(c){c=c[0].childNodes;for(var l,n,q=0,i;i=c[q++];)if(i.id==="mNotice-backdrop")l=i;else if(i.nodeType===
1)n=i;return{backdrop:l,content:n}}.apply(this,arguments);if(!a.iframe||!a.content)return false;b=d.one(a.backdrop);a=d.one(a.content);b.css("width:"+a.width()+"px;height:"+a.height())}function s(a){for(var b in a)return false;return true}function J(a){if(!window.iError)window.iError=[];window.iError.push({date:(new Date).toString(),info:a})}if(!e)throw Error("\u4f20\u9012\u8bbe\u7f6e\u53c2\u6570\uff01");var f=e.beside;if(this.length)f=d.one(this[0]);else{if(!f||typeof f!=="string"&&f.nodeType!==
1&&!f.length)throw Error("\u6307\u5b9a\u9700\u8981\u5f39\u6846\u7684\u8282\u70b9\u9009\u62e9\u5668\u6216\u8282\u70b9\uff01");f=d.one(f);if(!f.length)throw Error("\u6307\u5b9a\u9700\u8981\u5f39\u6846\u7684\u8282\u70b9\uff01");}if(!{INPUT:"INPUT",TEXTAREA:"TEXTAREA"}[f[0].nodeName])throw Error("\u6307\u5b9a\u7684\u8f93\u5165\u57df\u65e0\u6548\uff01");var m={x:0,y:0},u=e.offset&&e.offset.x,v=e.offset&&e.offset.y,h=e.request,k=e.localData,C=typeof e.template==="string"?e.template:undefined,E=e.mode===
"mTab"?"mTab":"",B=e.display,O=e.isClick===undefined?false:!!e.isClick,Q=e.isHover===undefined?false:!!e.isHover,I=typeof e.clickCallback==="function"?e.clickCallback:false,F=typeof e.theme==="string"?e.theme:"",w=typeof e.urlInTime==="function"?e.urlInTime:false,G=typeof e.rejects==="string"?e.rejects:false,x="",g,j,t,y={};if(e.offset&&(parseInt(u)||parseInt(v))){u&&(m.x=u);v&&(m.y=v)}if(!e.display&&typeof e.display!=="function")throw Error("\u6307\u5b9a\u6570\u636e\u6e32\u67d3\u51fd\u6570\uff01");
if(!h&&!k||h&&k)throw Error("\u6307\u5b9a\u552f\u4e00\u6570\u636e\u6e90\uff01");else if(h&&w){x=h.url;h.url=w(x);h.fn=function(a){if(a&&(a.length||!s(a)))d.ready(function(){y[h.url.substring(h.url.indexOf("?")+1)]=a;d.all("#mNotice-"+f[0].id).length?A(a):D(a)})};h.onTimeout=function(){J("\u670d\u52a1\u5668\u7aef\u54cd\u5e94\u8d85\u65f6\uff01")};h.err=function(){J("\u670d\u52a1\u5668\u7aef\u53d1\u751f\u9519\u8bef\uff01")};d.ajax(h)}else d.ready(function(){if(k&&(k.length||!s(k)))D(k)});d.ready(function(){d.one(window).on("resize",
o);d.one(window).on("scroll",o)});return{show:function(){j&&z(G)&&g.removeClass("none")},hide:function(){g.addClass("none")},position:p,update:function(){var a;h.url=w(x);a=h.url.substring(h.url.indexOf("?")+1);y[a]?A(y[a]):d.ajax(h)}}}})})(fish);
