(function(d){d.extend({mNotice:function(e){function z(a){var b=true;a=d.all(a);if(a.length){a.each(function(c){if(!(d.one(c).hasClass("none")||c.style.display==="none"))return b=false});return b}else return 1}function A(a){if(a=B.apply(g,[a,C])){f.html("");f.html(a);j=true}else j=false}function D(a,b){var c;K(g);if(c=B.apply(g,[a,C])){f=L(c,b);j=true;E==="mTab"&&M(E,g,b);N(g,f);O&&P(f,g);if(Q){R(f);S(f)}T(g,f);U(f,g);if(d.one(".mNotice-close",f).length)f.on("click",function(h){h=d.getTarget(h);d.one(h).hasClass("mNotice-close")&&
f.addClass("none")})}else j=false}function m(){if(!o){var a=document.createElement("iframe");a.id="mNotice-backdrop";fish.one(f).html("top",a);d.one(a).css("position:absolute;border:none;filter:alpha(opacity=0);opacity:0;z-index:-1");o=a}a=fish.one(f).width();var b=fish.one(f).height();fish.all(o).css("width:"+a+"px;height:"+b+"px")}function L(a,b){f=document.createElement("div");var c=d.one(f);f.id="mNotice-"+b;f.className=F?"mNotice-wrap none "+F:"mNotice-wrap none";c.css("position: absolute; z-index: 1000000;");
document.body.insertBefore(f,document.body.firstChild);f.innerHTML=a;m();return c}function M(a,b,c){a==="mTab"&&d.one("#mNotice-"+c).mTab({tab_tray:".mNotice-mTab-tab-tray",append:"current",content:".mNotice-mTab-content",fn:function(){p();m()}})}function N(a,b){a.on("focus",function(){d.all("body .mNotice-wrap").addClass("none");if(j&&z(G)){b.removeClass("none");l(b,a,n);m()}})}function K(a){a.on("click",function(){a[0].select()})}function P(a,b){a.on("click",function(c){c=d.getTarget(c);if(d.one(c).hasClass("mNotice-normal")){b.val(c.innerHTML);
b.attr("cid",c.getAttribute("cid"));b.attr("ctype",c.getAttribute("ctype"));b.addClass("color-normal");a.addClass("none");H&&H.apply(d.one(c),[b])}})}function R(a){a.on("mouseover",function(b){b=d.getTarget(b);if(d.one(b).hasClass("mNotice-normal")){d.all(".mNotice-normal",a).removeClass("mNotice-hover");d.one(b).addClass("mNotice-hover")}})}function S(a){a.on("mouseout",function(){d.all(".mNotice-normal",a).removeClass("mNotice-hover")})}function U(a,b){d.one(document).on("click",function(c){for(c=
d.getTarget(c);c!==null;){if(c.nodeType===1&&(c===b[0]||c.className.indexOf("mNotice-wrap")>-1))return;c=c.parentNode}a.addClass("none")})}function T(a,b){a.on("keydown",function(c){c=d.getEvent(c);key=c.keyCode||c.which;typeof key==="number"&&b.addClass("none")})}function l(a,b,c){var h=c;if(a&&a[0].nodeType===1&&b&&b[0].nodeType===1){a.css("left:-1000px;");c=d.one(window).width();d.one(window).height();var V=b.width(),W=b.height(),I=a.width();a.height();b=b.offset();d.one(document).scrollTop();
var q=d.one(document).scrollLeft();if(h&&!r(h)){h.x=typeof h.x==="number"?h.x:0;h.y=typeof h.y==="number"?h.y:0}else h={x:0,y:0};b.left-q>c-(b.left-q)&&c-(b.left-q)<I?a.css("left:"+(b.left+V-I-h.x)+"px"):a.css("left:"+(b.left+h.x)+"px");a.css("top:"+(b.top+W+h.y)+"px")}else l(f,g,c)}function p(){if(!(!f||f.hasClass("none"))){s&&clearTimeout(s);s=setTimeout(function(){l(f,g,n);m()},100)}}function r(a){for(var b in a)return false;return true}function J(a){if(!window.iError)window.iError=[];window.iError.push({date:(new Date).toString(),
info:a})}var t=fish.guid();if(!e)throw Error("\u4f20\u9012\u8bbe\u7f6e\u53c2\u6570\uff01");var g=e.beside;if(this.length)g=d.one(this[0]);else{if(!g||typeof g!=="string"&&g.nodeType!==1&&!g.length)throw Error("\u6307\u5b9a\u9700\u8981\u5f39\u6846\u7684\u8282\u70b9\u9009\u62e9\u5668\u6216\u8282\u70b9\uff01");g=d.one(g);if(!g.length)throw Error("\u6307\u5b9a\u9700\u8981\u5f39\u6846\u7684\u8282\u70b9\uff01");}if(!{INPUT:"INPUT",TEXTAREA:"TEXTAREA"}[g[0].nodeName])throw Error("\u6307\u5b9a\u7684\u8f93\u5165\u57df\u65e0\u6548\uff01");
var n={x:0,y:0},u=e.offset&&e.offset.x,v=e.offset&&e.offset.y,i=e.request,k=e.localData,C=typeof e.template==="string"?e.template:undefined,E=e.mode==="mTab"?"mTab":"",o,B=e.display,O=e.isClick===undefined?false:!!e.isClick,Q=e.isHover===undefined?false:!!e.isHover,H=typeof e.clickCallback==="function"?e.clickCallback:false,F=typeof e.theme==="string"?e.theme:"",w=typeof e.urlInTime==="function"?e.urlInTime:false,G=typeof e.rejects==="string"?e.rejects:false,x="",f,j,s,y={};if(e.offset&&(parseInt(u)||
parseInt(v))){u&&(n.x=u);v&&(n.y=v)}if(!e.display&&typeof e.display!=="function")throw Error("\u6307\u5b9a\u6570\u636e\u6e32\u67d3\u51fd\u6570\uff01");if(!i&&!k||i&&k)throw Error("\u6307\u5b9a\u552f\u4e00\u6570\u636e\u6e90\uff01");else if(i&&w){x=i.url;i.url=w(x);i.fn=function(a){if(a&&(a.length||!r(a)))d.ready(function(){y[i.url.substring(i.url.indexOf("?")+1)]=a;d.all("#mNotice-"+t).length?A(a):D(a,t)})};i.onTimeout=function(){J("\u670d\u52a1\u5668\u7aef\u54cd\u5e94\u8d85\u65f6\uff01")};i.err=function(){J("\u670d\u52a1\u5668\u7aef\u53d1\u751f\u9519\u8bef\uff01")};
d.ajax(i)}else d.ready(function(){if(k&&(k.length||!r(k)))D(k,t)});d.ready(function(){d.one(window).on("resize",p);d.one(window).on("scroll",p)});return{show:function(){setTimeout(function(){j&&z(G)&&f.removeClass("none")&&l()},0)},hide:function(){f.addClass("none")},position:l,update:function(){var a;i.url=w(x);a=i.url.substring(i.url.indexOf("?")+1);y[a]?A(y[a]):d.ajax(i)}}}})})(fish);
